### PR TITLE
Abstract Y/N Prompt Logic

### PR DESCRIPTION
**Pull request by s-eam**
Address #997 

- Modularize prompt logic into a separate function (fn_prompt_yn)
- Refactor scripts to utilize fn_prompt_yn
- Enhance Y/N prompt interface for usability

### CODE REVIEW

**Comment by UltimateByte** [comment]
Clever implementation, that's what i've been dreaming about :D

**Comment by dgibbs64** [comment]
@UltimateByte very exciting dreams you have ;-P. 

@s-eam Looks good. The main thing I would change is to get rid of core_prompt.sh and merge the code in  to core_messages.sh. I will have a look at this soon and merge. Thanks :)

**Comment by s-eam** [comment]
@UltimateByte Thanks! That means a lot to me!

@dgibbs64 I am eager to help! I have moved the logic into core_messages.sh for co-location with the other on-screen message functions.

**Comment by dgibbs64** [comment]
Thank you for your assistance. This has now been merged and ready for the next release :D

**Pull request merged**
