### PR TITLE
feat(newserver): Survive the Nights

### LINKED ISSUE #3387: [Server Request] Survive The Nights
## What game server would you like adding?

Survive the Nights

## Can you link to any tutorials or guides?
https://survivethenights.gamepedia.com/Hosting - Might be usefull!

Provide any useful documentation or resources that might help.

## Is the server on Steam?

* [X] Yes
* [ ] No

If yes Use SteamDB to get the appid. (https://steamdb.info).

1502300

https://steamdb.info/app/1502300/

## Is the server supported on Linux?
Yes and only Linux currently.
We only support Linux servers and do **not** support Wine.

* [x] Yes
* [ ] No

### PR DESCRIPTION
**Pull request by h3o66**
# Description

Add new server Survive the Nights

Fixes #3387

## Type of change

* [ ] Bug fix (a change which fixes an issue).
* [ ] New feature (change which adds functionality).
* [x] New Server (new server added).
* [ ] Refactor (restructures existing code).
* [ ] Comment update (typo, spelling, explanation, examples, etc).

## Checklist

PR will not be merged until all steps are complete.

* [x] This pull request links to an issue.
* [x] This pull request uses the `develop` branch as its base.
* [x] This pull request Subject follows the Conventional Commits standard.
* [x] This code follows the style guidelines of this project.
* [x] I have performed a self-review of my code.
* [x] I have checked that this code is commented where required.
* [x] I have provided a detailed with enough description of this PR.
* [x] I have checked If documentation needs updating.

## Documentation

If documentation does need updating either update it by creating a PR (preferred) or request a documentation update.
* User docs: https://github.com/GameServerManagers/LinuxGSM-Docs
* Dev docs: https://github.com/GameServerManagers/LinuxGSM-Dev-Docs

**Thank you for your Pull Request!**

### CODE REVIEW

**Comment by BlueSky-fur** [comment]
is this fully working currently?

**Comment by h3o66** [comment]
> is this fully working currently?

I did some basic tests now and the server is working fine with my basic tests.

**Comment by BlueSky-fur** [comment]
can confirm! works like a charm

**Review by dgibbs64 — APPROVED** [review]
tested and working

**Pull request merged**
