### PR TITLE
Fix dep checking for Centos8

### LINKED ISSUE #2525: CentOS 8 - Missing dependencies: python
I get the following when starting a new server. Fresh install of everything, CentOS, LGSM, etc. I realize in CentOS 8 we have python2 or python3 now, and I've used "alternatives" command to get a /usr/bin/python path in place. Still get this message on every restart.

https://hastebin.com/bakixavibi

`[qzrust1@li102-221 ~]$ ./rustserver start
[ .... ] Starting rustserver: RustWarning! Missing dependencies: python`

### PR DESCRIPTION
**Pull request by Frisasky**
# Description

In centos 8 you must specify which version of python you wanna install

> [root@localhost ~]# yum install mailx postfix curl wget bzip2 gzip unzip python binutils bc jq tmux glibc.i686 libstdc++ libstdc++.i686 libcurl.i686
Extra Packages for Enterprise Linux 8 - x86_64  233 kB/s | 1.9 MB     00:08
Last metadata expiration check: 0:00:01 ago on Fri 04 Oct 2019 12:12:00 AM CST.
Package curl-7.61.1-8.el8.x86_64 is already installed.
Package wget-1.19.5-7.el8_0.1.x86_64 is already installed.
Package bzip2-1.0.6-26.el8.x86_64 is already installed.
Package gzip-1.9-4.el8.x86_64 is already installed.
Package unzip-6.0-41.el8.x86_64 is already installed.
No match for argument: python
There are following alternatives for "python": python2, python36
Package binutils-2.30-49.el8.x86_64 is already installed.
Package bc-1.07.1-5.el8.x86_64 is already installed.
Package tmux-2.7-1.el8.x86_64 is already installed.
Package libstdc++-8.2.1-3.5.el8.x86_64 is already installed.
Error: Unable to find a match

So the dep list on lgsm website also needs to be updated, we can add python2 as required dep in dependencies list, it would results no match found in centos7 but there's no harm either.

Fixes #2525

## Type of change

* [x] Bug fix (change which fixes an issue).
* [ ] New feature (change which adds functionality).
* [ ] New Server (new server added).
* [ ] Refactor (restructures existing code).
* [ ] Comment update (typo, spelling, explanation, examples, etc).

## Checklist

PR will not be merged until all steps are complete.

* [x] This pull request links to an issue.
* [x] This pull request uses the `develop` branch as its base.
* [ ] This code follows the style guidelines of this project.
* [ ] I have performed a self-review of my own code.
* [ ] I have checked that this code is commented where required.
* [ ] I have provided a detailed enough description of this PR.
* [ ] I have checked If documentation needs updating.

## Documentation

If documentation does need updating either update it by creating a PR (preferred) or request a documentation update.
* User docs: https://github.com/GameServerManagers/LinuxGSM-Docs
* Dev docs: https://github.com/GameServerManagers/LinuxGSM-Dev-Docs

**Thank you for your Pull Request!**

### CODE REVIEW

**Comment by dgibbs64** [comment]
The other question is can we move to python 3. I think the python requirement is only for gsquery

**Comment by Frisasky** [comment]
ok, changed to python36

**Comment by Frisasky** [comment]
it seems there no compatibility problem running monitor script under python3

**Comment by dgibbs64** [comment]
yeah I saw this yesterday.  Just looked at the availability of python 3 and they are available on all supported distros. So I think its time to move across to python 3. @Frisasky please can you update gsquery to use python 3 in this PR

**Comment by Frisasky** [comment]
i know nothing about programming, sorry

**Comment by dgibbs64** [comment]
just this needed changing for me `#! /usr/bin/env python3`. WIll need to check this works with the other distros

**Pull request merged**
