### PR TITLE
Release/161113

### PR DESCRIPTION
**Pull request by dgibbs64**

### CODE REVIEW

**Comment by UltimateByte** [comment]
How come travis fials ?

**Comment by UltimateByte** [comment]
https://travis-ci.org/GameServerManagers/LinuxGSM/builds/175405095#L598

```
Test starting:
[ .... ] Starting jc2-server:     fetching check_logs.sh...OK
    fetching check_ip.sh...OK
    fetching info_config.sh...OK
    fetching check_config.sh...OK
    fetching fix_steamcmd.sh...OK
[  OK  ] Fix jc2-server: Applying steamclient.so general fix: Just Cause 2
    fetching logs.sh...OK
failed to connect to server: Connection refused
[ FAIL ] Starting jc2-server: Unable to start JC2-MP Server
command_start.sh exiting with code: 1
=================================
Expected result: PASS
Actual result: FAIL
[ FAIL ] TEST FAILED
 exiting with code: 1
The command "bash tests/tests_jc2server.sh" exited with 1.
```

**Comment by dgibbs64** [comment]
no idea. I will have to figure it out

**Comment by marvinl97** [comment]
I already tested some things yesterday. Nothing worked.

Error output when running these lines, I think. (I don't know the specific command; probably the first.)
Apparently happening since #1118

**Comment by dgibbs64** [comment]
check_ip appears to be the issue here. As the server will not start with multiple ip addresses. I will run a few more tests

**Comment by UltimateByte** [comment]
WP

**Comment by dgibbs64** [comment]
Still failing even though my tests work on my VPS. I cannot see why this is an issue. I see no reason for this. There is no issue with the build. I will merge to master anyway and see the results.

**Pull request merged**
