### PR TITLE
Fix for subnets

### PR DESCRIPTION
**Pull request by T1MOXA**

### CODE REVIEW

**Comment by T1MOXA** [comment]
An example of my configuration:
```
server@user:~$ ip -o -4 addr
1: lo    inet 127.0.0.1/8 scope host lo\       valid_lft forever preferred_lft forever
2: enp3s0    inet 11.11.11.11/24 brd 11.11.11.255 scope global enp3s0\       valid_lft forever preferred_lft forever
2: enp3s0    inet 11.11.11.11 peer 11.11.2.1/32 brd 11.11.11.11 scope global enp3s0\       valid_lft forever preferred_lft forever
```

**Comment by dgibbs64** [comment]
@T1MOXA please can you describe why this change is required. I'm sure its probably correct but I don't fully understand it.

**Comment by T1MOXA** [comment]
```
server@user:~$ ip -o -4 addr
1: lo    inet 127.0.0.1/8 scope host lo\       valid_lft forever preferred_lft forever
2: enp3s0    inet 11.11.22.11/24 brd 11.11.22.255 scope global enp3s0\       valid_lft forever preferred_lft forever
2: enp3s0    inet 11.11.22.11 peer 22.22.22.1/32 brd 11.11.22.11 scope global enp3s0\       valid_lft forever preferred_lft forever
```

`ip -o -4 addr|awk '{print $4}'|grep -oe '\([0-9]\{1,3\}\.\?\)\{4\}'|grep -vc 127.0.0` return `2`
And server doesn't start.

`ip -o -4 addr|awk '{print $4}'|grep -oe '\([0-9]\{1,3\}\.\?\)\{4\}'|sort -u|grep -v 127.0.0` return `11.11.22.11`
The server starts normally.

**Comment by UltimateByte** [comment]
In my case, (with docker installed which explains the 172.17.X.X IP) on a CentOS VM:

```bash
# ip -o -4 addr
1: lo    inet 127.0.0.1/8 scope host lo\       valid_lft forever preferred_lft forever
2: eth0    inet 154.41.xxx
xxx/23 brd 154.41.67.255 scope global eth0\       valid_lft forever preferred_lft forever
3: docker0    inet 172.17.0.1/16 scope global docker0\       valid_lft forever preferred_lft forever
```

Original code output:
```bash
# ip -o -4 addr| awk '{print $4}' | grep -oe '\([0-9]\{1,3\}\.\?\)\{4\}' | grep -v 127.0.0
154.41.xxx.xxx
172.17.0.1
# ip -o -4 addr| awk '{print $4}' | grep -oe '\([0-9]\{1,3\}\.\?\)\{4\}' | grep -vc 127.0.0
2
```

New code output:
```bash
# ip -o -4 addr|awk '{print $4}'|grep -oe '\([0-9]\{1,3\}\.\?\)\{4\}'|sort -u|grep -v 127.0.0
154.41.xxx.xxx
172.17.0.1
# ip -o -4 addr|awk '{print $4}'|grep -oe '\([0-9]\{1,3\}\.\?\)\{4\}'|sort -u|grep -vc 127.0.0
2
```

Got the same kind of output on my Debian machine (which has a dozen IP), so no issue in the first place. Could possibly your original issue come from the fact that you have two times the same IP displayed in `ip -o -4 addr`, but the second occurrence doesn't have the mask in it?

Any case, your PR doesn't seem to hurt, except we like to add spaces between pipes `|` for clarity but this doesn't affect code execution.

**Pull request merged**
