### PR TITLE
Jedi Knight II: Jedi Outcast

### LINKED ISSUE #1202: [Server Request] Jedi Knight II – Jedi Outcast
Hey, I'm working on a Jedi Outcast server [here](https://github.com/nateberkopec/LinuxGSM/tree/jk2).

The server needs a few of the assets from the game itself - assets0.pk3, assets1.pk3, and assets2.pk3. I figure OK, I'll get them from Steam - but since there's no Linux *client*, it refuses to download:

```
ERROR! Failed to install app '6030' (Invalid platform)
```

Can you tell me where I've gone wrong and what to do next? 

connects #1251

### PR DESCRIPTION
**Pull request by dgibbs64**
# Description

Fixes #1202

## Type of change

* [ ] Bug fix (change which fixes an issue).
* [ ] New feature (change which adds functionality).
* [x] New Server (new server added).
* [ ] Refactor (restructures existing code).
* [ ] Comment update (typo, spelling, explanation, examples, etc).
* [ ] This change requires a documentation update.

## Checklist

* [x] This code follows the style guidelines of this project.
* [x] This pull request links to an issue.
* [x] This pull request uses the `develop` branch as its base.
* [x] I have provided Co-author details below.
* [x] I have performed a self-review of my own code.
* [x] I have squashed commits.
* [x] I have commented my code, particularly in hard to understand areas.
* [x] I have made corresponding changes to the documentation if required.

## Provide Github Email

Fill out below info or tick box below:
```
Co-authored-by: John Doe <name@example.com>
```

- [ ] I do not wish to provide an email. I am aware this will hide me as the author of this commit.

All pull requests will now be squashed to create a tidy commit history and simplify changelog creation. You can provide either your own email or a GitHub-provided no-reply email.

When a PR is squashed the author becomes the person who squashed the PR. This removes you as the author of your own PR.
The only workaround for this is to add your details as a co-author. More info about co-authors can be found [here](https://help.github.com/en/articles/creating-a-commit-with-multiple-authors).

### CODE REVIEW

**Comment by dgibbs64** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/LinuxGSM/LinuxGSM/pullRequest?prid=3726128&bid=13110890)

**Comment by dgibbs64** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/LinuxGSM/LinuxGSM/pullRequest?prid=3726128&bid=13110890)

**Comment by dgibbs64** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/LinuxGSM/LinuxGSM/pullRequest?prid=3726128&bid=13110890)

**Comment by Frisasky** [comment]
still getting "Invalid platform" error despite "sSteamCmdForcePlatformType" in steamcmd launch parameter

**Comment by dgibbs64** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/LinuxGSM/LinuxGSM/pullRequest?prid=3726128&bid=13110890)

**Comment by dgibbs64** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/LinuxGSM/LinuxGSM/pullRequest?prid=3726128&bid=13110890)

**Comment by dgibbs64** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/LinuxGSM/LinuxGSM/pullRequest?prid=3726128&bid=13110890)

**Comment by nateberkopec** [comment]
Awesome! Thanks for your work @dgibbs64!

**Pull request merged**
