### PR TITLE
feat(dev): add new developer command for parsing distro details

### PR DESCRIPTION
**Pull request by MicLieg**
# Description

## Parse Game Details
- This PR renames `command_dev_details.sh` to `command_dev_parse_game_details.sh` to better reflect the purpose of the command.
- Now every variable that `info_game.sh` can provide will be displayed if set.
- The advantage is that no matter what gameserver is currently installed the command `./gameserver parse-game-details` will display every variable that LinuxGSM (`info_game.sh`) could parse from the games config file.
K8s6GnfbA1

## Parse Distro Details
- This PR adds a new command, similar to `command_dev_parse_game_details.sh`, which will display every set variable that `info_distro.sh` can provide (with a few exceptions).
RDh4p9Z0eb

Fixes N/A

## Type of change

-   [ ] Bug fix (a change which fixes an issue).
-   [x] New feature (a change which adds functionality).
-   [ ] New Server (new server added).
-   [ ] Refactor (restructures existing code).
-   [ ] Comment update (typo, spelling, explanation, examples, etc).

## Checklist

PR will not be merged until all steps are complete.

-   [ ] This pull request links to an issue.
-   [x] This pull request uses the `develop` branch as its base.
-   [x] This pull request subject follows the Conventional Commits standard.
-   [x] This code follows the style guidelines of this project.
-   [x] I have performed a self-review of my code.
-   [x] I have checked that this code is commented where required.
-   [x] I have provided a detailed enough description of this PR.
-   [x] I have checked if documentation needs updating.
    - I will add documentation once I get feedback on whether this PR will be merged.

## Documentation

If documentation does need updating either update it by creating a PR (preferred) or request a documentation update.

-   User docs: https://github.com/GameServerManagers/LinuxGSM-Docs
-   Dev docs: https://github.com/GameServerManagers/LinuxGSM-Dev-Docs

**Thank you for your Pull Request!**

### CODE REVIEW

**Review by dgibbs64 — APPROVED** [review]

**Review by dgibbs64 — APPROVED** [review]

**Review by dgibbs64 — CHANGES_REQUESTED** [review]
This line need updating. https://github.com/GameServerManagers/LinuxGSM/blob/045c55c4dac6166f67fa35cc2c78d60b88e98985/.github/workflows/details-check.yml#L86

Also please make sure you update the required docs.

Apart from that I like the update. Thank you

**Comment by MicLieg** [comment]
You're absolutley right! I didn't think of that.

I'll submit a PR for the docs in a couple of hours 👍

**Comment by MicLieg** [comment]
FYI, I'm going to keep the new documentation for this to a minimum for now, and expand it as soon as https://github.com/GameServerManagers/LinuxGSM/pull/4527 and the other two doc PRs are merged.

After that i'm planning to give all the docs some attention and will be refactoring them quite a bit.

**Comment by MicLieg** [comment]
_This comment was posted to the wrong PR:_

For archiving purposes, I'm posting the script I used to extract most of the variables:

```bash
#!/bin/bash

# Define the root directory to search in
ROOT_DIR="./lgsm/modules"

# Find all .sh files and process them
find "$ROOT_DIR" -type f -name "*.sh" | while read -r file; do
    echo "File: $file"
    # Extract variables, including those using += for appending
    # Remove duplicates in the same file, ignoring comments
    # and focusing on simple VARIABLE=value or VARIABLE+=value patterns
    # without the value, =, or + character
    grep -Eo '^[[:space:]]*[^#[:space:]]+\+?=[^=]+' "$file" | \
    sed -E 's/\+?=.*//' | \
    sort | uniq | \
    sort | \
    while read -r variable; do
        echo "  - $variable"
    done
    echo # Add a blank line for better readability between files
done

```

**Pull request merged**
