### PR TITLE
refactor(backup): unify backupdir on all configs

### LINKED ISSUE #2398: Backup dir not the same for all configs
## User Story

Some configs have 
```
backupdir="${lgsmdir}/backup"
```
While others have
```
backupdir="${rootdir}/backup"
```
all should be the first. refactor required to move backups if the dir changes.

## Basic info

* Command: Backup

### PR DESCRIPTION
**Pull request by h3o66**
# Description

Please include a summary of the change and which issues is fixed

Fixes #2398 

## Type of change

* [ ] Bug fix (change which fixes an issue).
* [ ] New feature (change which adds functionality).
* [ ] New Server (new server added).
* [x] Refactor (restructures existing code).
* [ ] Comment update (typo, spelling, explanation, examples, etc).

## Checklist

PR will not be merged until all steps are complete.

* [x] This pull request links to an issue.
* [x] This pull request uses the `develop` branch as its base.
* [x] This code follows the style guidelines of this project.
* [x] I have provided Co-author details below.
* [x] I have performed a self-review of my own code.
* [ ] I have checked that this code is commented where required.
* [ ] I have provided a detailed enough description of this PR.
* [ ] I have checked If documentation needs updating.

## Provide Github Email

Fill out below info or tick box below:
```
Co-authored-by: Christian Birk <chris.h3o66@gmail.com>
```

### CODE REVIEW

**Comment by dgibbs64** [comment]
The only issue I see is that the old backups will then be in the wrong directory. I think something needs to be done to migrate them to the new directory.

**Comment by h3o66** [comment]
Added little migration function for this commit

**Comment by dgibbs64** [comment]
@h3o66 Need permission to this one as well please. In fact please could you check all outstanding PR's  :+1:

**Comment by h3o66** [comment]
> @h3o66 Need permission to this one as well please. In fact please could you check all outstanding PR's

is there already

**Pull request merged**
