### PR TITLE
fix(wipe): resolve random seed not working

### LINKED ISSUE #2915: RustServer: Random seed not random
OS: Ubuntu server 18.04
latest version of LGSM

I have a rust server well 4, none of which will generate a random seed is I leave seed to “” I just gens the same map over and over.
./rustserver wipe and ./rustserver wipeall does not change the map seed
```
`##################################
######## Instance Settings ########
##################################

PLACE INSTANCE SETTINGS HERE
These settings will apply to a specific instance
Server Settings
Server Start Settings | https://docs.linuxgsm.com/configuration/start-parameters
More settings available after install in serverfiles/server/rust-server/server.cfg
ip=“69.69.69.69”
port=“28023”
rconport=“28024”
rconpassword=“nope”
rconweb=“1” # Value is: 1 for Facepunch’s web panel; 0 for RCON tools like Rusty or Rustadmin
servername=“Test Server”
maxplayers=“2”

Advanced Start Settings
seed="" # default random; range : 1 to 2147483647 ; used to change or reproduce a procedural map
salt="" # default random; range : unknown range ; used to recover a known setting from an existing map
worldsize=“1000” # default 3000; range : 1000 to 6000 ; map size in meters
saveinterval=“300” # Auto-save in seconds
tickrate=“100” # default 30; range : 15 to 100

Server Start Command | https://docs.linuxgsm.com/configuration/start-parameters#additional-parameters
fn_parms(){

Specific to Rust
if [ -n “${seed}” ]; then
# If set, then add to start parms
conditionalseed="+server.seed ${seed}"
else
# Keep randomness of the number if not set
conditionalseed=""
fi
if [ -n “${salt}” ]; then
# If set, then add to start parms
conditionalsalt="+server.salt ${salt}"
else
# Keep randomness of the number if not set
conditionalsalt=""
fi
parms="-batchmode +server.ip ${ip} +server.port ${port} +server.tickrate ${tickrate} +server.hostname "${servername$
}

LinuxGSM Settings
Notification Alerts
(on|off)
Display IP | https://docs.linuxgsm.com/alerts#display-ip
displayip=""

More info | https://docs.linuxgsm.com/alerts#more-info
postalert=“off”
postdays=“7”
posttarget=“https://hastebin.com”

Discord Alerts | https://docs.linuxgsm.com/alerts/discord
discordalert=“off”
discordwebhook=“webhook”

Email Alerts | https://docs.linuxgsm.com/alerts/email
emailalert=“off”`
```

### PR DESCRIPTION
**Pull request by dgibbs64**
# Description

Get ransom seed working

Fixes #2915

## Type of change

* [x] Bug fix (a change which fixes an issue).
* [ ] New feature (change which adds functionality).
* [ ] New Server (new server added).
* [ ] Refactor (restructures existing code).
* [ ] Comment update (typo, spelling, explanation, examples, etc).

## Checklist

PR will not be merged until all steps are complete.

* [x] This pull request links to an issue.
* [x] This pull request uses the `develop` branch as its base.
* [x] This pull request Subject follows the Conventional Commits standard.
* [x] This code follows the style guidelines of this project.
* [x] I have performed a self-review of my code.
* [x] I have checked that this code is commented where required.
* [x] I have provided a detailed with enough description of this PR.
* [x] I have checked If documentation needs updating.

## Documentation

If documentation does need updating either update it by creating a PR (preferred) or request a documentation update.
* User docs: https://github.com/GameServerManagers/LinuxGSM-Docs
* Dev docs: https://github.com/GameServerManagers/LinuxGSM-Dev-Docs

**Thank you for your Pull Request!**

### CODE REVIEW

**Review by h3o66 — CHANGES_REQUESTED** [review]
Add coreutils to the dependencys for rust to be sure that this works

**Comment by dgibbs64** [comment]
> Add coreutils to the dependencys for rust to be sure that this works

Looks like coreutils a standard package that is installed so I don't think it's needed. 
https://wiki.debian.org/coreutils

**Review by h3o66 — APPROVED** [review]
fine with me then

**Comment by Yurii-Rizzlioni** [comment]
Is this implementation complete? When I read through the code it looks to work except when the server is started the stored seed isnt applied? I've simply modified my _default config to get the seed it seed is "" for the moment.

**Pull request merged**
