### PR TITLE
Allow setting of level for, e.g. HapisIsland, or levelurl for custom maps

### PR DESCRIPTION
**Pull request by RFC1920**
This adds the ability to easily choose a custom level or custom map.

### CODE REVIEW

**Comment by dgibbs64** [comment]
Looks good. I prefer to avoid too many if statements in the config though. I might move the if's to a module instead. It may also need to be sorted alongside the extra parms pr #2183

**Comment by RFC1920** [comment]
FWIW the section I changed here was an if/else structure.  Agreed it should probably be somewhere else and also include the extraparms from #2183.

**Comment by dgibbs64** [comment]
Need an opinion on this from a Rust admin

**Comment by dgibbs64** [comment]
Features of this PR have been added via #2711 Thank you

**Pull request closed without merging**
