### PR TITLE
fix(mods): get5 download change to github

### LINKED ISSUE #4018: [BUG] Fail to install get5 mod
On a fresh server install after `./csgoserver mi install`, type 'get5' and confirm.
I'm unable to install get5 from the script, can you investigate please ?

Thanks !

```
 Installing Get 5
 =================================
 clearing mod download directory /home/csgoserver1/lgsm/mods/tmp...OK
 creating mod download directory /home/csgoserver1/lgsm/mods/tmp...OK
 fetching  ...FAIL 
```

### PR DESCRIPTION
**Pull request by h3o66**
# Description

Fix install of get5 mod

Fixes #4018 

## Type of change

-   [x] Bug fix (a change which fixes an issue).
-   [ ] New feature (change which adds functionality).
-   [ ] New Server (new server added).
-   [ ] Refactor (restructures existing code).
-   [ ] Comment update (typo, spelling, explanation, examples, etc).

## Checklist

PR will not be merged until all steps are complete.

-   [x] This pull request links to an issue.
-   [x] This pull request uses the `develop` branch as its base.
-   [x] This pull request Subject follows the Conventional Commits standard.
-   [x] This code follows the style guidelines of this project.
-   [x] I have performed a self-review of my code.
-   [x] I have checked that this code is commented where required.
-   [x] I have provided a detailed with enough description of this PR.
-   [x] I have checked If documentation needs updating.

## Documentation

If documentation does need updating either update it by creating a PR (preferred) or request a documentation update.

-   User docs: https://github.com/GameServerManagers/LinuxGSM-Docs
-   Dev docs: https://github.com/GameServerManagers/LinuxGSM-Dev-Docs

**Thank you for your Pull Request!**

### CODE REVIEW

**Comment by Cyberschorsch** [comment]
Thank you for your contribution! 

I am not sure if switching to github is the best approach, at least without adding more information since Github is pretty strict with unauthenticated requests via their API. 

Maybe there is a way to get the newest release without querying the REST API on every mods-install command?

**Comment by h3o66** [comment]
> Thank you for your contribution!
> 
> I am not sure if switching to github is the best approach, at least without adding more information since Github is pretty strict with unauthenticated requests via their API.
> 
> Maybe there is a way to get the newest release without querying the REST API on every mods-install command?

yes, i am aware of this, but we need to fully restructure the whole mod command for this. ( or add a way to add a github api token )

The jenkins build system does not seem to have anymore the builds for get5, so this was the fastest way to do this.

Not sure if there is a better way to do a version check without he api at all.

**Comment by ringvold** [comment]
Hi!
I'm completely new here, but it seems like this way of fetching mods is not new in this project. All the other csgo mods except from Get5 are fetched from github. Is this PRs changed considered to be so impactful in terms of traffic that is should not be merged until there is found another solution?

**Comment by Cyberschorsch** [comment]
The impact for this single change is not that high so this is not a reason to not merge it. As @h3o66 already wrote: We should find a better way of handling those mods in general but not in this PR.

**Pull request merged**
