### PR TITLE
[WIP] New mods

### PR DESCRIPTION
**Pull request by dgibbs64**
This is a branch that I found. So I made a PR

### CODE REVIEW

**Comment by Bara** [comment]
And [Accelerator](https://forums.alliedmods.net/showthread.php?t=277703) would be nice.

**Comment by borzaka** [comment]
Many CSGO mods can't be used together. So basically besides Source mod (metamod, sourcemod, and some basic mod), only one mod installation is recommended, because probably they will break each other. Or if you are a pro in mods and server configuration, you can disable/enable mods, but after installation out-of-the box they won't work.

For example: Pug Setup and Get5 almost identical in function, but with different purpose. Installing both is not a good idea.

**Comment by dgibbs64** [comment]
This will need further investigation

**Comment by saintplay** [comment]
The user should be aware of the mods compatibility, if they install both mods, deleting the mods should be enough to fix the server.

This pull request needs some updates, there are some undocumented changes, code formatting, the urls don't match latest releases, etc.

I don't know if the author will continue to fix this issues.
I could create a new PR if it's necessary @dgibbs64

**Comment by dgibbs64** [comment]
@saintplay I agree. These issues need to be addressed before merged. I won't be able to get to this for a while as its a lower priority. But If you are willing to contact the PR author and either collaborate or PR this to improve it that would be great. The mods commands do need some improvement.

**Pull request closed without merging**
