### PR TITLE
Trying out a hypothesis on the travis failures.

### PR DESCRIPTION
**Pull request by cedarlug**

### CODE REVIEW

**Comment by UltimateByte** [comment]
Does the travis test machine lacks a package or something?
If it works only with sudo command available, that's the only reason I can think of.

**Comment by dgibbs64** [comment]
Looks like we have a pass. Well done. What was required to get it to work? Was it just sudo?

**Comment by dgibbs64** [comment]
#1186

**Comment by cedarlug** [comment]
Ultimately just the one-line change to the sudo entry in .travis.yml allows it to go through.

In more detail, there is a large difference between the two environments with just this one simple change.

It appears that permitting sudo allows the development environment to push through an apt-get upgrade.

In two of the latter test runs, I dumped the packages on the system for comparison.

[Here's a diff of the two package lists](https://transfer.sh/mjU2t/lgsm-travis).


I was expecting at most a dozen packages to be different between the two development environments, but 457 differences between the packages installed with/without sudo was surprising.

**Comment by cedarlug** [comment]
`sudo: required` == travis success. #1186

**Comment by UltimateByte** [comment]
You must be a living god for f**k sake.
That's a one liner fix, but amazing work behind it!

**Pull request merged**
