### PR TITLE
Fixes Steam Login fail when password includes a '$'

### LINKED ISSUE #1203: LGSM Games that require Steam login fail when password includes $
Hello! After trying to install a 7 Day to Die server today, I found out that the reason the install script kept failing was because of a randomly generated password I was using the included a $. 

A simple fix for this problem would be to change the quotes on the variable in the install script from " to '. 

Thanks!

### PR DESCRIPTION
**Pull request by ChaosMTA**
Fixes #1203

### CODE REVIEW

**Comment by UltimateByte** [comment]
Thanks a lot for the fix.
Would you be kind enough to cancel this pull request and redo it, but to the develop branch ?
As per https://github.com/GameServerManagers/LinuxGSM/wiki/Branching

**Comment by ChaosMTA** [comment]
Hotfixes branch off master, considering this blocks users from logging into SteamCMD I considered it a critical fix, however I can do it off the develop branch if you'd rather @UltimateByte

**Comment by UltimateByte** [comment]
I'm not sure it's so critical since it's the first time the issue appears to occur, but if it's important to you, than it might be something to consider. 
Maybe you can open a second PR to the develop branch and keep this one open, and @dgibbs64 will decide what to do. :)

**Comment by ChaosMTA** [comment]
Done from develop into develop here:
https://github.com/GameServerManagers/LinuxGSM/pull/1227

Up to you which you wish to use.

**Comment by UltimateByte** [comment]
Perfect, thanks :)
Maybe both :p

**Comment by dgibbs64** [comment]
@UltimateByte you shoudl be able to change the branch to develop yourself. Its a feature that GitHub added a few months back. Its really useful

**Comment by UltimateByte** [comment]
@dgibbs64 I didn't know about that, thanks for the info.

**Pull request closed without merging**
