### PR TITLE
[WIP]SCP: Secret Laboratory 

### LINKED ISSUE #1995: [Server Request] SCP Secret Laboratory
## What game server would you like adding?

SCP: Secret Laboratory

## Can you link to any tutorials or guides?

https://steamcommunity.com/app/700330/discussions/1/1692662484248805180/

## Is the server on Steam?

* [x] Yes
* [ ] No

If yes Use SteamDB to get the appid. (https://steamdb.info).

786920

## Is the server supported on Linux?

We only support Linux servers and do not support Wine.

* [x] Yes
* [ ] No

### PR DESCRIPTION
**Pull request by frisasky1**
# Description

one problem still remain, the details command cannot fetch required info, i would post default config file in link below hoping someone could look into that

https://pastebin.com/j0LqZu3Q

Fixes #1995

## Type of change

* [ ] Bug fix (change which fixes an issue)
* [ ] New feature (change which adds functionality)
* [X] New Server (new server added)
* [ ] Refactor (restructures existing code)
* [ ] This change requires a documentation update

## Checklist

* [ ] My code follows the style guidelines of this project
* [X] This pull request links to an issue
* [X] This pull request uses the `develop` branch as its base 
* [X] I have performed a self-review of my own code
* [ ] I have squashed commits
* [ ] I have commented my code, particularly in hard to understand areas
* [ ] I have made corresponding changes to the documentation if required

### CODE REVIEW

**Comment by dgibbs64** [comment]
Why has this been closed?

**Comment by frisasky1** [comment]
I accidentally deleted the entire repo  : (

**Comment by dgibbs64** [comment]
the diffs can be seen still if needed

**Comment by dgibbs64** [comment]
@33Fraise33 any update on this?

**Pull request closed without merging**
