### PR TITLE
feat(new server): mcbserver

### LINKED ISSUE #2243: [Server Request] Minecraft Bedrock Edition
## What game server would you like adding?

Minecraft Bedrock Edition

## Can you link to any tutorials or guides?

Server files can be found here:
https://www.minecraft.net/en-us/download/server/bedrock/

## Is the server on Steam?

* [ ] Yes
* [X] No

## Is the server supported on Linux?

We only support Linux servers and do not support Wine.

* [X] Yes
* [ ] No

### PR DESCRIPTION
**Pull request by marvinlehmann**
# Description

Added support for Minecraft Bedrock.

Now I'm just wondering if I should add a update logic like for the normal Minecraft (update_minecraft.sh)? I could retrieve the download url & version with:
`curl -s "https://www.minecraft.net/en-us/download/server/bedrock/" | grep -o 'https://minecraft.azureedge.net/bin-linux/[^"]*'`

And the current version from the server log:

> [2019-10-24 21:05:23 INFO] Starting Server
> [2019-10-24 21:05:23 INFO] Version 1.12.1.1

I also don't know what to put in for the engine name as Java isn't used for this Minecraft version.

Fixes #2243

## ToDo
* [x] revert githuburl in install_config.sh before merge
* [ ] revert repo settings in linuxgsm.sh before merge
* [x] add config (https://github.com/GameServerManagers/Game-Server-Configs/pull/90)
* [ ] add update logic like for normal Minecraft? (update_minecraft.sh)
* [ ] set engine?

## Type of change

* [ ] Bug fix (change which fixes an issue).
* [ ] New feature (change which adds functionality).
* [X] New Server (new server added).
* [ ] Refactor (restructures existing code).
* [ ] Comment update (typo, spelling, explanation, examples, etc).

## Checklist

PR will not be merged until all steps are complete.

* [X] This pull request links to an issue.
* [X] This pull request uses the `develop` branch as its base.
* [X] This code follows the style guidelines of this project.
* [X] I have performed a self-review of my own code.
* [X] I have checked that this code is commented where required.
* [X] I have provided a detailed enough description of this PR.
* [ ] I have checked If documentation needs updating.

## Documentation

If documentation does need updating either update it by creating a PR (preferred) or request a documentation update.
* User docs: https://github.com/GameServerManagers/LinuxGSM-Docs
* Dev docs: https://github.com/GameServerManagers/LinuxGSM-Dev-Docs

**Thank you for your Pull Request!**

### CODE REVIEW

**Comment by Frisasky** [comment]
it would be nice if update script from this repo could be integrated into this PR
https://github.com/TapeWerm/MCscripts

**Comment by marvinlehmann** [comment]
Hey, I added update functionality but it's different from the script you linked. I directly unzip the new files into the serverfiles folder without overwriting configs. But I'm not sure what the best/"correct" way would be.

**Comment by dgibbs64** [comment]
I will be looking at this as soon as I can.

**Comment by dgibbs64** [comment]
done basic tests and looks good. monitor query needs looking at

**Comment by marvinlehmann** [comment]
Apparently gamedig only supports custom bedrock servers like NukkitX or PocketMine-MP and not the official one. The official server uses RakNet as network engine.

With gsquery we could send the following string:
```
self.query_prompt_string = b'\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\xff\x00\xfe\xfe\xfe\xfe\xfd\xfd\xfd\xfd\x12\x34\x56\x78\x00\x00\x00\x00\x00\x00\x00\x00'
```
0x01= Message ID: Unconnected Ping (1 Byte)
0x0000000000000000 = time stuff??? (8 Bytes) - doesn't seem to matter
0x00ffff00fefefefefdfdfdfd12345678 = RakNet Offline message data ID (16 Bytes)
0x0000000000000000 = RakNet Client GUID??? (8 Bytes) - doesn't seem to matter

**Comment by dgibbs64** [comment]
i tested the query and got it working with the vanilla download

**Comment by dgibbs64** [comment]
I am doing a refactor on monitor function to handle games without and engine and the best way to migrate over to _default.cfg. I think this should be completed before I complete mcb. It's annoying but I think its needed. So hand tight :)

**Comment by marvinlehmann** [comment]
OK! =)
Nevertheless we could use "bedrock" as the engine name for Minecraft BE because it's called "Bedrock Engine" on many websites and official Minecraft Twitter after browsing a bit. :)

Furthermore I responded to an existing gamedig issue where another user also couldn't query an official bedrock server which simply doesn't work for me too. https://github.com/sonicsnes/node-gamedig/issues/139

**Comment by dgibbs64** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/LinuxGSM/LinuxGSM/pullRequest?prid=4381038&bid=14864249)

**Comment by dgibbs64** [comment]
this should be the last pr now before release. Hopefully can get it merged this evening

**Pull request merged**
