### PR TITLE
feat(skeleton): New command skeleton

### LINKED ISSUE #585: [LGSM] Skeleton directory
An idea that I like is from an issue raised a long while ago #185. Which was the ability for a user to create there own skeleton directory that could be copied post install allowing them to deploy there custom scripts and configs right away. I already do this with my nmrih servers mainly as a backup. I have all my custom files in a bitbucket repo that I just download when required. This would be great for speeding up deployment of servers and backing up of configs/custom files that differ from the vanilla install.

### PR DESCRIPTION
**Pull request by dgibbs64**
# Description

A new command that generates a skel directory of empty directories that mirror your game server. This is useful for anyone who wants to backup custom maps and configs to re-apply them later to another server.

Fixes #585

## Type of change

* [ ] Bug fix (a change which fixes an issue).
* [x] New feature (change which adds functionality).
* [ ] New Server (new server added).
* [ ] Refactor (restructures existing code).
* [ ] Comment update (typo, spelling, explanation, examples, etc).

## Checklist

PR will not be merged until all steps are complete.

* [x] This pull request links to an issue.
* [x] This pull request uses the `develop` branch as its base.
* [x] This pull request Subject follows the Conventional Commits standard.
* [x] This code follows the style guidelines of this project.
* [x] I have performed a self-review of my code.
* [x] I have checked that this code is commented where required.
* [x] I have provided a detailed with enough description of this PR.
* [x] I have checked If documentation needs updating.

## Documentation

If documentation does need updating either update it by creating a PR (preferred) or request a documentation update.
* User docs: https://github.com/GameServerManagers/LinuxGSM-Docs
* Dev docs: https://github.com/GameServerManagers/LinuxGSM-Dev-Docs

**Thank you for your Pull Request!**

### CODE REVIEW

**Comment by dgibbs64** [comment]
I will update docs soon

**Review by h3o66 — CHANGES_REQUESTED** [review]
to be sure i would add cpio as dependency overall

**Comment by dgibbs64** [comment]
docs added

**Review by h3o66 — APPROVED** [review]
looks good

**Pull request merged**
