### PR TITLE
[WIP] feat(newserver) Waterfall

### PR DESCRIPTION
**Pull request by DUDU54**
Waterfall is a fork of the BungeeCord software, with improved Forge support and more features.
It's a proxy for minecraft server, it allow servers owner to connect multiple server
it come with an API to select version and update when needed

waterfall version selection

## Type of change

* [ ] Bug fix (change which fixes an issue).
* [ ] New feature (change which adds functionality).
* [X] New Server (new server added).
* [ ] Refactor (restructures existing code).
* [ ] Comment update (typo, spelling, explanation, examples, etc).
* [ ] This change requires a documentation update.

## Checklist

* [X] This code follows the style guidelines of this project.
* [X] This pull request uses the `develop` branch as its base.
* [X] I have performed a self-review of my own code.
* [ ] I have squashed commits.
* [X] I have commented my code, particularly in hard to understand areas.
* [ ] I have made corresponding changes to the documentation if required.

## Provide Github Email

```
Co-authored-by: DUDU54 <14166148+DUDU54@users.noreply.github.com>
```

### CODE REVIEW

**Comment by dgibbs64** [comment]
Sorry, it's taking me a while. Been very busy. Trying to catch up :)

**Review by h3o66 — CHANGES_REQUESTED** [review]
Please rebase and resolve the conflicts

**Comment by dgibbs64** [comment]
this is an important pr to do with Minecraft improvements. @h3o66 Minecraft was on my list after Ark and Rust to improve

**Comment by h3o66** [comment]
closing this in favour of #3292

**Pull request closed without merging**
