### PR TITLE
feat(newserver): Last Oasis

### LINKED ISSUE #2808: [Server Request] Last Oasis
## What game server would you like adding?

Last Oasis - Dedicated Server

## Can you link to any tutorials or guides?

Provide any useful documentation or resources that might help.

## Is the server on Steam?

* [x] Yes
* [ ] No

If yes Use SteamDB to get the appid. (https://steamdb.info).

920720

## Is the server supported on Linux?

We only support Linux servers and do **not** support Wine.

* [x] Yes
* [ ] No

### PR DESCRIPTION
**Pull request by Claiyc**
# Description

If applied, this will add a new server Last Oasis.

Fixes #2808 

## Type of change

* [ ] Bug fix (a change which fixes an issue).
* [ ] New feature (change which adds functionality).
* [x] New Server (new server added).
* [ ] Refactor (restructures existing code).
* [ ] Comment update (typo, spelling, explanation, examples, etc).

## Checklist

PR will not be merged until all steps are complete.

* [x] This pull request links to an issue.
* [x] This pull request uses the `develop` branch as its base.
* [x] This pull request Subject follows the Conventional Commits standard.
* [x] This code follows the style guidelines of this project.
* [x] I have performed a self-review of my code.
* [x] I have checked that this code is commented where required.
* [x] I have provided a detailed with enough description of this PR.
* [x] I have checked If documentation needs updating.

## Documentation

If documentation does need updating either update it by creating a PR (preferred) or request a documentation update.
* User docs: https://github.com/GameServerManagers/LinuxGSM-Docs
* Dev docs: https://github.com/GameServerManagers/LinuxGSM-Dev-Docs

**Thank you for your Pull Request!**

### CODE REVIEW

**Comment by Claiyc** [comment]
About the missing configfile on installation: Afaik you *can* edit the Game.ini and add some configuration stuff there, although you normally do that via the webinterface that last oasis provides automatically. That's why I didn't provide a default config, as it would be emtpy anyways. An emtpy Game.ini will be generated on first server stop, so the "missing configfile" warning disappears then.

**Review by h3o66 — APPROVED** [review]
Looks good and would be needed for the next release

**Comment by dgibbs64** [comment]
Keep crashing for me. Can you confirm that it is running OK?

**Comment by Claiyc** [comment]
@dgibbs64 Can‘t check rn as I am currently in greece (and will be for another week). I tested it on deb10 when I created this pr and everything worked smoothly on first attempt.

**Comment by dgibbs64** [comment]
Having to do some git wizardry to remove the lo commits from develop.

**Comment by dgibbs64** [comment]
@Claiyc looks like I have to resgister the server for it to run I think. Which involves buying the game

**Comment by Claiyc** [comment]
@dgibbs64 yes, that is definitely the case. Makes sense that the server crashes for you then. I opened a pr in the lgsm docs github with some more explanation: https://github.com/GameServerManagers/LinuxGSM-Docs/pull/77

**Comment by dgibbs64** [comment]
Thanks looks like I will have to buy a copy to test this one out

**Comment by Claiyc** [comment]
@dgibbs64 Even if you don‘t want to play the game, it‘s definitely worth a look as it is some really exciting technology I‘ve never seen in any other game server before. Also take a look at the server request issue linked to this pr, I linked some official references there.

**Comment by dgibbs64** [comment]
Thanks. I am going to drop a message on their discord to see if they would be willing to dift me a copy. Sometimes devs are willing 👍

**Pull request closed without merging**
