### PR TITLE
Update to new stable version of sourcemod

### PR DESCRIPTION
**Pull request by Cripix**

### CODE REVIEW

**Comment by UltimateByte** [comment]
Needs to be tested (not sure if just changing the version branch is enough).
Ref: https://www.sourcemod.net/

**Comment by Bara** [comment]
@UltimateByte should be enough at the first look. @Cripix or @iNilo anyone tested this?

**Comment by T1MOXA** [comment]
https://forums.alliedmods.net/showthread.php?t=308912

**Comment by Bara** [comment]
I've tested it and works fine:

> meta version
Metamod:Source version 1.10.7-dev
Built from: https://github.com/alliedmodders/metamod-source/commit/20c72b5
Build ID: 963:20c72b5
Loaded As: Valve Server Plugin
Compiled on: Jul  7 2018
Plugin interface version: 15:14
SourceHook version: 5:5
http://www.metamodsource.net/

> sm version
 SourceMod Version Information:
    SourceMod Version: 1.9.0.6241
    SourcePawn Engine: 1.9.0.6241, jit-x86 (build 1.9.0.6241)
    SourcePawn API: v1 = 4, v2 = 12
    Compiled on: Jul  7 2018 07:13:38
    Built from: https://github.com/alliedmodders/sourcemod/commit/07f8043
    Build ID: 6241:07f8043
    http://www.sourcemod.net/

**Comment by Shivam16a** [comment]
+1 vote for Sourcemod update to 1.9

**Pull request merged**
