### PR TITLE
Factorio headless support

### PR DESCRIPTION
**Pull request by Krisseck**
(I know there is already a pull request for Factorio #1072, but I wasn't sure how to merge my code to it)

Took me a while but here is a working version of Factorio headless server support! It fetches the server from Factorio.com, sets the config and all that. 

Factorio/fctrserver has reference to my Github repo, but just change that and it should work fine :)

### CODE REVIEW

**Comment by dgibbs64** [comment]
Brilliant work. I will review it and merge once I have tested etc. 👍

**Comment by dgibbs64** [comment]
I am testing look great however the updater does not work.  Its unable to detect the version as its missing in the console log

```
   0.067 Operating system: Linux (Ubuntu 16.04)
   0.067 Program arguments: "./bin/x64/factorio" "--start-server" "/home/lgsm/fctrserver/serverfiles/save1.zip" "--server-settings" "/home/lgsm/fctrserver/serverfiles/data/server-settings.json" "--port" "34197" "--rcon-port" "34198" "--rcon-password" "factorio"
   0.067 Read data path: /home/lgsm/fctrserver/serverfiles/data
   0.067 Write data path: /home/lgsm/fctrserver/serverfiles
   0.067 Binaries path: /home/lgsm/fctrserver/serverfiles/bin
   0.078 Running in headless mode
   0.080 Loading mod core 0.0.0 (data.lua)
   0.085 Loading mod base 0.13.20 (data.lua)
   0.194 Checksum for core: 303426634
   0.195 Checksum for mod base: 1460151764
   0.582 Info PlayerData.cpp:47: Local player-data.json unavailable
   0.582 Info PlayerData.cpp:52: Cloud player-data.json unavailable
   0.583 Custom inputs active: 0
   0.584 Factorio initialised
   0.585 Info Router.cpp:558: Router peerID(65535) shutting down.
   0.585 Info Router.cpp:594: Router state -> Disconnected
   0.680 Info MultiplayerManager.cpp:1000: networkTick(0) mapTick(-1) changing state from(Ready) to(PreparedToHostGame)
   0.680 Info MultiplayerManager.cpp:1000: networkTick(0) mapTick(-1) changing state from(PreparedToHostGame) to(CreatingGame)
   0.680 Loading map /home/lgsm/fctrserver/serverfiles/save1.zip
   0.714 Info Scenario.cpp:127: Map version 0.13.20-0
   0.823 Checksum for script /home/lgsm/fctrserver/serverfiles/temp/currently-playing/control.lua: 900459546
   0.841 Info PosixUDPSocket.cpp:50: Opening socket at port 34197
   0.841 Info Router.cpp:594: Router state -> Connected
   0.841 Info Synchronizer.cpp:56: NetworkTick(0) initialized Synchronizer local peer(0) latency(6).
   0.842 Hosting game at port 34197, peerID 0, session magic 3251
   0.842 Info HttpSharedState.cpp:44: Downloading https://auth.factorio.com/generate-server-padlock
   1.254 Info HttpSharedState.cpp:108: Status code: 200
   1.255 Info AuthServerConnector.cpp:106: Obtained serverPadlock for serverHash (Kk9NX6snDweptF1VG3OUA5huPeIg89ke) from the auth server.
   1.255 Info MultiplayerManager.cpp:1000: networkTick(0) mapTick(0) changing state from(CreatingGame) to(InGame)
   1.255 Info NetworkInputHandler.cpp:45: mapTick(0) networkTick(0) initialized NetworkInputHandler local peer(0).
   1.255 Info RemoteCommandProcessor.cpp:94: Starting RCON interface at port 34198
   1.373 Info MultiplayerManager.cpp:1531: Received peer info for peer(0) username(<server>).
   1.373 Info MultiplayerManager.cpp:1147: networkTick(6) mapTick(0) received stateChanged peerID(0) oldState(Ready) newState(CreatingGame)
   1.373 Info MultiplayerManager.cpp:1147: networkTick(6) mapTick(0) received stateChanged peerID(0) oldState(CreatingGame) newState(InGame)

```

**Comment by Krisseck** [comment]
I had typo in my regexp for checking the current build in log files, tested locally and seemed to be okay now.

**Comment by dgibbs64** [comment]
Thanks I will test again

**Pull request merged**
