### PR TITLE
Update Oxide mod download URLs

### PR DESCRIPTION
**Pull request by lukespragg**
Per http://oxidemod.org/threads/new-snapshot-build-server-and-download-locations.23770/

### CODE REVIEW

**Comment by UltimateByte** [comment]
Thanks !
Is this a critical fix that needs to be solved asap, or can it wait until @dgibbs64 comes back?

**Comment by lukespragg** [comment]
@UltimateByte, per the announcement on the 14th, the Snapshots repo was slatted to be removed beginning of the month and was removed today. So any users that use LGSM wouldn't be able to install Oxide with the old URL.

**Comment by dgibbs64** [comment]
Im on it :)

**Comment by dgibbs64** [comment]
Done. Thank you for submitting this!

**Comment by lukespragg** [comment]
No problem, I thought you guys had already gotten to it so it didn't even cross my mind until someone reported it to me. Thanks!

**Pull request merged**
