### PR TITLE
During update, check against branch being public.

### LINKED ISSUE #3072: command ./rustserver u does not work
Hi
command ./rustserver u does not work, message as in the picture 

https://imageshack.com/i/pn4rVk7Vj

Thank You

### LINKED ISSUE #3079: Ark Server update does not work.
Hello, can any help me with this error I have?

My arkserver runs with ark version  313.57 I want to update it to 314.5 with the `./arkserver update` command, but I get this error: 
```
[ FAIL ] Updating arkserver: Checking remote build: SteamCMD
arkserver@v2202007106712123820:~$
```
I have the LGSM version: v20.5.1 and never had any errors with updating the server, until now.

Here are the server details, because the server runs on version 313.57:
```
Distro Details
=================================
Distro:    Debian GNU/Linux 10 (buster)
Arch:      x86_64
Kernel:    4.19.0-9-amd64
Hostname:  v2202007106712123820
Uptime:    0d, 9h, 44m
tmux:      tmux 2.8
glibc:     2.28

Server Resource
=================================
CPU
Model:      AMD EPYC 7702P 64-Core Processor
Cores:      4
Frequency:  1996.238MHz
Avg Load:   0.63, 0.25, 0.12

Memory
Mem:       total  used   free  cached  available
Physical:  16GB   1.1GB  15GB  5.9GB   15GB
Swap:      0B     0B     0B

Storage
Filesystem:  /dev/sda3
Total:       157G
Used:        54G
Available:   97G

Network
Interface:  eth0
IP:         xx.xx.xx.xx

Game Server Resource Usage
=================================
CPU Used:  25.1%
Mem Used:  0.7%   128MB

Storage
Total:        23G
Serverfiles:  20G
Backups:      56K

ARK: Survival Evolved Server Details
=================================
Server name:      xxxxxxxxxxxxxx
App ID:           376030
Server IP:        xxxxxxxxxxxxxx
Server password:  NOT SET
Admin password:   xxxxxxxxxxxxxx
Maxplayers:       70
Default map:      TheIsland
Master server:    not listed
Status:           ONLINE

arkserver Script Details
=================================
Script name:            arkserver
LinuxGSM version:       v20.5.1
glibc required:         2.15
Discord alert:          off
Email alert:            off
IFTTT alert:            off
Mailgun (email) alert:  off
Pushbullet alert:       off
Pushover alert:         off
Rocketchat alert:       off
Slack alert:            off
Telegram alert:         off
Update on start:        off
User:                   arkserver
Location:               /home/arkserver
Config file:            /home/arkserver/serverfiles/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini

Backups
=================================
No Backups created

Command-line Parameters
=================================
./ShooterGameServer TheIsland?AltSaveDirectoryName=TheIsland?listen?MultiHome=xx.xx.xx.xx?MaxPlayers=70?QueryPort=27016?RCONPort=27021?Port=7779?ServerAdminPassword=xxxxxxxxxxxxxx -automanagedmods -crossplay -PublicIPForEpic=xx.xx.xx.xx

Ports
=================================
Change ports by editing the parameters in:
/home/arkserver/lgsm/config-lgsm/arkserver

Useful port diagnostic command:
netstat -atunp | grep ShooterGame

DESCRIPTION  DIRECTION  PORT   PROTOCOL
> Game       INBOUND    7779   udp
> RAW        INBOUND    7780   udp
> Query      INBOUND    27016  udp
> RCON       INBOUND    27021  tcp

Status: ONLINE
```
Thanks for helping me :-)

### LINKED ISSUE #3106: Garry´s Mod Server update function is broken (./gmodserver update)
## User Story
gmodserver update function doesn´t work at the moment. update process everytime looks like this:

[ OK ] Updating gmodserver: Checking local build: SteamCMD
[ FAIL ] Updating gmodserver: Checking remote build: SteamCMD

I triple checked my firewall and dependencies, every needed port is open.

## Information about my system:
Distro Details
=================================
Distro:    Ubuntu 18.04.5 LTS
Arch:      x86_64
Kernel:    4.15.0-88-generic
Hostname:  Ubuntu-1804
Uptime:    192d, 14h, 0m
tmux:      tmux 2.6
glibc:     2.27

Server Resource
=================================
CPU         
Model:      AMD Ryzen 5 3600 6-Core Processor
Cores:      12
Frequency:  2120.548MHz
Avg Load:   0.31, 0.30, 0.29

Memory     
Mem:       total  used   free  cached  available
Physical:  63GB   7.9GB  55GB  32GB    55GB
Swap:      32GB   0B     32GB

Storage
Filesystem:  /dev/md2
Total:       437G
Used:        30G
Available:   385G

Network
Interface:   enp34s0
Link Speed:  1000Mb/s
IP:           [censored]

Game Server Resource Usage
=================================
CPU Used:  0.8%
Mem Used:  0.2%  179MB

Storage
Total:        7.5G
Serverfiles:  6.6G
Backups:      100K

Garry's Mod Server Details
=================================
Server name:  [censored]      
App ID:           4020
Server IP:        [censored]:27015
Server password:  ********
RCON password:    ********
Players:          0/16
Current map:      ttt_bb_teenroom_b2
Default map:      ttt_bb_teenroom_b2
Game mode:        terrortown
Tick rate:        66
Master server:    listed
Status:           ONLINE

gmodserver Script Details
=================================
Script name:            gmodserver
LinuxGSM version:       v20.5.1
glibc required:         2.15
Discord alert:          off
Email alert:            off
IFTTT alert:            off
Mailgun (email) alert:  off
Pushbullet alert:       off
Pushover alert:         off
Rocketchat alert:       off
Slack alert:            off
Telegram alert:         off
Update on start:        off
User:                   gmodserver
Location:               /home/gmodserver
Config file:            /home/gmodserver/serverfiles/garrysmod/cfg/gmodserver.cfg

Backups
=================================
No Backups created

Command-line Parameters
=================================
./srcds_run -game garrysmod -strictportbind -ip  [censored] -port 27015 -tickrate 66 +host_workshop_collection 2034936295 -authkey ******** +clientport 27005 +tv_port 27020 +gamemode terrortown +map ttt_bb_teenroom_b2 +sv_setsteamaccount ******** +servercfgfile gmodserver.cfg -maxplayers 16 -disableluarefresh

DESCRIPTION  DIRECTION  PORT   PROTOCOL
> Game/RCON  INBOUND    27015  tcp/udp
> SourceTV   INBOUND    27020  udp
< Client     OUTBOUND   27005  udp
Status:	ONLINE

All relevant logs that I could find:

[dev-debug-function-order.log](https://github.com/GameServerManagers/LinuxGSM/files/5573144/dev-debug-function-order.log)
[dev-debug.log](https://github.com/GameServerManagers/LinuxGSM/files/5573145/dev-debug.log)
[steamlogs.zip](https://github.com/GameServerManagers/LinuxGSM/files/5573155/steamlogs.zip)

### LINKED ISSUE #3129: [CS GO] Server update
Good evening, today all the servers stopped starting at once, what could be the problem I can't figure out, can you help in what direction to look for the reason?

csgo-jbm@ds1492:~$ ./csgoserver start
[  OK  ] Updating csgoserver: Checking for update: SteamCMD

Update available
* Local build: 5946707
* Remote build:
* Branch: public
https://steamdb.info/app/740/

[ START ] Updating csgoserver: SteamCMD
Branch: public
Redirecting stderr to '/home/csgo-jbm/.local/share/Steam/logs/stderr.txt'
/tmp/dumps is not owned by us - delete and recreate
Unable to delete /tmp/dumps. Continuing anyway.
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
Success! App '740' already up to date.
Complete! Updating csgoserver: SteamCMD

### LINKED ISSUE #3131: Update fails
Some people and me too are experiencing issues updating gameservers:

[ FAIL ] Updating rustserver: Checking remote build: SteamCMD

At the moment my Rustserver is not fetching updates.
I've updated LGSM also but it didn't help

### PR DESCRIPTION
**Pull request by JoinedSenses**
# Description

This change fixes the update command for those on public branches. Possibly needs testing and confirmation.

Fixes #3072 
Fixes #3079
Fixes #3106
Fixes #3129
Fixes #3131 

## Type of change
Check if branch var is 'public' to use correct `remoteBuild` execution.

* [X] Bug fix (a change which fixes an issue).
* [ ] New feature (change which adds functionality).
* [ ] New Server (new server added).
* [ ] Refactor (restructures existing code).
* [ ] Comment update (typo, spelling, explanation, examples, etc).

## Checklist

PR will not be merged until all steps are complete.

* [X] This pull request links to an issue.
* [?] This pull request uses the `develop` branch as its base.
* [X] This pull request Subject follows the Conventional Commits standard.
* [X] This code follows the style guidelines of this project.
* [X] I have performed a self-review of my code.
* [X] I have checked that this code is commented where required.
* [X] I have provided a detailed with enough description of this PR.
* [X] I have checked If documentation needs updating.

### CODE REVIEW

**Comment by EnriqCG** [comment]
This needs to be merged in ASAP. It's breaking all of our servers with the recent CSGO update. The fix is working for me 👍

**Review by jamesonp — APPROVED** [review]
This fixes the `[ FAIL ] Updating arkserver: Checking remote build: SteamCMD` on Ubuntu 20.04.

**Comment by xSL0W** [comment]
I can confirm this is a problem for me too. (debian10)

**Review by Grimston — APPROVED** [review]
Working as intended

```
./rustserver update
[  OK  ] Updating rustserver: Checking for update: SteamCMD

No update available
* Local build: 5984887
* Remote build: 5984887
* Branch: public
https://steamdb.info/app/258550/
```

**Comment by carek5** [comment]
For me on Debian 9 (Stretch) not work ./rustserver u

[ FAIL ] Updating arkserver: Checking remote build: SteamCMD...

**Comment by JoinedSenses** [comment]
> For me on Debian 9 (Stretch) not work ./rustserver u
> 
> [ FAIL ] Updating rustserver: Checking remote build: SteamCMD...

Verify you updated/replaced the file on the server

**Comment by LubricantJam** [comment]
This seems to be the fix for me too on Ubuntu 18.04 for CS:GO, cheers.

**Comment by carek5** [comment]
I confirm, it works for Rust Server

change line 45 of home/ACCOUNT/lgsm/functions/update_steamcmd.sh to:
elif [ -n "${branch}" ]&&[ "${branch}" != "public" ]; then

**Comment by h3o66** [comment]
Did someone test if this as well works with a branch name set ?

**Comment by dgibbs64** [comment]
I will get this into a hotfix.

**Pull request merged**
