### PR TITLE
fix(vintsserver): Add ip= to _default.cfg

### LINKED ISSUE #3658: [BUG]vintsserver monitor ip unavailable
## User Story

The vintsserver monitor command does not seem to be using ${configip} to query. "Querying port: tcp: UNAVAILABLE:42420"

## Basic info

* **Game:** [vintserver]
* **Command:** [Monitor]
* **LinuxGSM version:** [v21.4.1]

### PR DESCRIPTION
**Pull request by Claiyc**
# Description

This adds the ip= -variable to vintsserver _default.cfg

Fixes #3658 

## Type of change

* [x] Bug fix (a change which fixes an issue).
* [ ] New feature (change which adds functionality).
* [ ] New Server (new server added).
* [ ] Refactor (restructures existing code).
* [ ] Comment update (typo, spelling, explanation, examples, etc).

## Checklist

PR will not be merged until all steps are complete.

* [x] This pull request links to an issue.
* [x] This pull request uses the `develop` branch as its base.
* [x] This pull request Subject follows the Conventional Commits standard.
* [x] This code follows the style guidelines of this project.
* [x] I have performed a self-review of my code.
* [x] I have checked that this code is commented where required.
* [x] I have provided a detailed with enough description of this PR.
* [x] I have checked If documentation needs updating.

## Documentation

If documentation does need updating either update it by creating a PR (preferred) or request a documentation update.
* User docs: https://github.com/GameServerManagers/LinuxGSM-Docs
* Dev docs: https://github.com/GameServerManagers/LinuxGSM-Dev-Docs

**Thank you for your Pull Request!**

### CODE REVIEW

**Comment by Claiyc** [comment]
Please link this to #3658 before merging.

**Review by johnoclockdk — APPROVED** [review]

**Comment by dgibbs64** [comment]
ip= is normaly used for start parameters.  Doesnt vint server use a config?

**Comment by johnoclockdk** [comment]
@dgibbs64 look like it https://wiki.vintagestory.at/index.php?title=Server_Config

**Comment by Claiyc** [comment]
Okay I did not know that. Then the option would be to fetch the ip via info_game directly from the config.

**Pull request closed without merging**
