### PR TITLE
Command: mods-install/update/remove

### LINKED ISSUE #631: Integration with mods for applicable games
Many server admins want to have an easy way to add/remove SourceMod plugins. Would it be possible to add support for managing SourceMod plugins through LGSM? Or at least having the ability to install SourceMod and MetaMod by default for any games that support it? 

It would be cool to be able to have a package manager for SourceMod plugins that was a part of LGSM that would not only install the plugins but also create the default CVARs etc in the config file.

### PR DESCRIPTION
**Pull request by UltimateByte**
Installing and keeping external game mods updated have never been so easy.

Introducing
````bash
./gameserver mods-install
./gameserver mods-update
./gameserver mods-remove
````

Fixes #631

demo

**Features**
- Install / update / remove a mod
- Get latest mod URL when needed by scraping host's website
- Show available mods for a given game/engine (allows for excluding games)
- Keep track of all installed mods in order to update or remove them
- Ability to set updates policies (for example: NOUPDATE for a mod that shouldn't be overwritten)
- Builds a file list of any installed mod in order to cleanly remove any file from it
- Ability to preserve config files upon mod update
- Handles many possible errors
- Allows for specific post-install fixes
- Allows for easy new mods support
- Loads of comments and descriptions.

**Adding mods support**
Everything has been made to allow for adding a mod with two line edits in best case scenari:
1) Add your mod info into mods_list.sh, in the form of mod_info_name=() array
2) Add this array to mods_global_array=()
3) (OPTIONAL) Scrape latest URL if needed, using fn_mods_scrape_urls functions.
4) (OPTIONAL), Apply some post-install tasks if needed with fn_postinstall_tasks inside mods_core.sh

It will might be polished a little before merging.
Please, point out anything you think could be improved.

### CODE REVIEW

**Comment by maximelafarie** [comment]
Can't wait to see you merge it!

**Comment by UltimateByte** [comment]
Will make a 2nd review/pass during the next day. Some things can be improved in terms of code structure, and some comments are probably wrong. Need to chill a bit. :p

**Comment by maximelafarie** [comment]
That's right my friend! Good luck and keep up the good work! 😄

**Comment by UltimateByte** [comment]
Well @dgibbs64 As far as i'm concerned, it is ready.

**Comment by Siburnett** [comment]
Very nice stuff here! Am i correct in thinking this will be for any mod from Steam workshop ? (If so i assume Ark mods will work with this ? Keen to test this out on my test server.

**Comment by dgibbs64** [comment]
Been testing. this is brilliant!! I have found a bug though https://hastebin.com/ciqaxemise.bash

**Comment by UltimateByte** [comment]
OK, thanks. Will check this out asap.

**Comment by UltimateByte** [comment]
CentOS issue most likely happened here
`/usr/bin/curl -s --fail -L -o /home/lgsm/cssserver/lgsm/tmp/mods/ http://cdn.probablyaserver.com/sourcemod//`

**Comment by UltimateByte** [comment]
What happens if you throw this line to your centos box ?
Should return SM latest filename.
````bash
wget "http://www.gsptalk.com/mirror/sourcemod/?MD" -q -O -| grep "sourcemod-" | grep "\-linux" | head -n1 | awk -F '>' '{ print $3 }' | awk -F '<' '{ print $1}'
````

**Comment by UltimateByte** [comment]
Appended required changes.

Also fixes #1187

**Comment by UltimateByte** [comment]
Well, I think i'm done and happy with it now.
Here are some outputs you can get.

picture

**Comment by UltimateByte** [comment]
Note for myself:
Check that totalmods variable works as intended by watching logs.
After reviewing code, i'm not so sure it's being used as it should.

**Comment by UltimateByte** [comment]
Fixed wrong counter.
@dgibbs64 Only weird thing now is for some reason, file remove listing is sometimes on 2 lines rather than one.

Example output:

````ultimatebyte@game:~$ ./gmodserver mr

Garry's Mod addons/mods
=================================

Remove addons/mods
=================================
ulx - ULX - Admin Panel (requires ULib)
ulib - ULib - Complete Framework
utime - UTime - Keep track of players play time
metamod - MetaMod - Plugins Framework
darkrpmodification - DarkRP Modification - Customize DarkRP settings

Enter an addon/mod to install (or exit to abort): darkrpmodification
Warning! You are about to remove darkrpmodification.
 * Any custom files/configuration will be removed.
Continue? [Y/n]y
removing DarkRP Modification
* 46 files to be removed
* location: /home/ultimatebyte/serverfiles/garrysmod/addons
OK
removing DarkRP Modification 46 / 46 : darkrpmodification-master/README.md...OK
removing darkrpmodification-files.txt...OK
removing darkrpmodification from ...OK
DarkRP Modification removed
ultimatebyte@game:~$ ./gmodserver mr

Garry's Mod addons/mods
=================================

Remove addons/mods
=================================
ulx - ULX - Admin Panel (requires ULib)
ulib - ULib - Complete Framework
utime - UTime - Keep track of players play time
metamod - MetaMod - Plugins Framework

Enter an addon/mod to install (or exit to abort): metamod
Warning! You are about to remove metamod.
 * Any custom files/configuration will be removed.
Continue? [Y/n]y
removing MetaMod
* 22 files to be removed
* location: /home/ultimatebyte/serverfiles/garrysmod
OK
removing MetaMod 1 / 22 : addons/metamod.vdf...OK
removing MetaMod 22 / 22 : addons/metamod/metaplugins.ini...OK
removing metamod-files.txt...OK
removing metamod from ...OK
MetaMod removed
````

**Pull request merged**
