### PR TITLE
feat(newserver): soulmask

### LINKED ISSUE #4587: [Server Request]: Soulmask
### Game server

Soulmask

### Linux support

- [X] Yes

### Steam

Yes

### Steam appid

3017300

### Guides

https://pimylifeup.com/soulmask-server-linux/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by intel44**
# Description

Adding server compatibility for soulmask : https://store.steampowered.com/app/2646460/Soulmask/

**AppID** : 3017300

**Based on documentation** :
  - https://soulmask.fandom.com/wiki/Private_Server
  - https://pimylifeup.com/soulmask-server-linux/

**Specific development** : The game uses telnet as server manager. In order to stop the game server cleanly, an attempt is made to save the world before stopping the server. If telnet fails, the server is killed via tmux (standard).
A similar process existed for 7 Days to Die. Development was based on what already existed.

Fixes #4587 

## Type of change

-   [ ] Bug fix (a change which fixes an issue).
-   [ ] New feature (a change which adds functionality).
-   [x] New Server (new server added).
-   [ ] Refactor (restructures existing code).
-   [ ] Comment update (typo, spelling, explanation, examples, etc).

## Checklist

PR will not be merged until all steps are complete.

-   [x] This pull request links to an issue.
-   [x] This pull request uses the `develop` branch as its base.
-   [x] This pull request subject follows the Conventional Commits standard.
-   [x] This code follows the style guidelines of this project.
-   [x] I have performed a self-review of my code.
-   [x] I have checked that this code is commented where required.
-   [x] I have provided a detailed enough description of this PR.
-   [x] I have checked if documentation needs updating.

## Documentation

**PR** : https://github.com/GameServerManagers/LinuxGSM-Docs/pull/106

If documentation does need updating either update it by creating a PR (preferred) or request a documentation update.

-   User docs: https://github.com/GameServerManagers/LinuxGSM-Docs
-   Dev docs: https://github.com/GameServerManagers/LinuxGSM-Dev-Docs

### CODE REVIEW

**Comment by dgibbs64** [comment]
Is this ready for review?

**Comment by dgibbs64** [comment]
currently testing. Confirmed crashing on ubuntu 24.04

**Review by dgibbs64 — APPROVED** [review]

**Comment by heusmich** [comment]
Hi,

Is there already a release date for the Soulmask server in LinuxGSM?

**Comment by intel44** [comment]
> Hi,
> 
> Is there already a release date for the Soulmask server in LinuxGSM?


It's already merged in `develop` branch. You can deploy it like this using env variable : (or wait for new release)

As usual, Download linuxgsm.sh
```sh
curl -Lo linuxgsm.sh https://linuxgsm.sh && chmod +x linuxgsm.sh
```

Set these environement variables in your current terminal in order to use the development branch :
```sh
export LGSM_GITHUBBRANCH=develop
```

And launch server installation as usual with `lunixgsm.sh` :
```sh
./linuxgsm.sh smserver
```

Don't hesitate to give me any feedback !

**Comment by intel44** [comment]
@dgibbs64 I'd like to take this opportunity to thank you for his quick adjustment and validation

I've been using lgsm for over 8 years now, and having created a similar library in bash several years ago on the professional side in order to centralise our processes, I can tell you that it's a pleasure to learn and discover on the dev side !

I wish you all the best for the future, and our paths should cross again depending on the games that come along 😉

**Pull request merged**
