### PR TITLE
feat(newserver): add Velocity Proxy

### LINKED ISSUE #3436: [Server Request] Velocity Proxy for minecraft
## What game server would you like adding?

Velocity Proxy for minecraft server

## Can you link to any tutorials or guides?

https://velocitypowered.com/
https://velocitypowered.com/wiki
https://velocitypowered.com/wiki/users/getting-started/

https://github.com/VelocityPowered/Velocity

## Is the server on Steam?

* [ ] Yes
* [x] No

## Is the server supported on Linux?

* [x] Yes
* [ ] No

### PR DESCRIPTION
**Pull request by h3o66**
# Description

Please include a summary of the change and which issues are fixed.

Fixes #3436

## Type of change

* [ ] Bug fix (a change which fixes an issue).
* [ ] New feature (change which adds functionality).
* [x] New Server (new server added).
* [ ] Refactor (restructures existing code).
* [ ] Comment update (typo, spelling, explanation, examples, etc).

## Checklist

PR will not be merged until all steps are complete.

* [x] This pull request links to an issue.
* [x] This pull request uses the `develop` branch as its base.
* [x] This pull request Subject follows the Conventional Commits standard.
* [x] This code follows the style guidelines of this project.
* [x] I have performed a self-review of my code.
* [x] I have checked that this code is commented where required.
* [x] I have provided a detailed with enough description of this PR.
* [x] I have checked If documentation needs updating.

## Documentation

If documentation does need updating either update it by creating a PR (preferred) or request a documentation update.
* User docs: https://github.com/GameServerManagers/LinuxGSM-Docs
* Dev docs: https://github.com/GameServerManagers/LinuxGSM-Dev-Docs

**Thank you for your Pull Request!**

### CODE REVIEW

**Comment by h3o66** [comment]
TOBD: check if upload of the default config needed or not

**Comment by h3o66** [comment]
Updated to create the new stip command "shutdown"

**Comment by h3o66** [comment]
Added port message, config parsing and dependency for java 11

**Comment by h3o66** [comment]
Added a bit more of config parsing.
I did not see the need to add the config to our repo, at is created at the first start.

The current latest version does not seem to be a stable one, that is the only curlprint for this.

**Comment by dgibbs64** [comment]
Is this ready to merge?

**Comment by h3o66** [comment]
> Is this ready to merge?

From my side this is ready.
Would be good if someone else can test this before this is released.

**Pull request merged**
