### PR TITLE
#1418 factorio experimental

### PR DESCRIPTION
**Pull request by Digital-Storm**
Added Factorio Experimental build support. Needed to update the core_dl to extract the file properly, as well as added a new variable to switch from "stable" to "experimental". Updated version checking to return 1 line instead of more than 1, which would break the comparison as well.

### CODE REVIEW

**Comment by dgibbs64** [comment]
Very happy with this well done!!. merging in to develop branch ready for next release

**Comment by ClaytonSmith** [comment]
Is there documentation on how to use this new feature?

**Comment by wizpig64** [comment]
@ClaytonSmith Here's what worked for me:

1. Download the fctrserver script [from the develop branch](https://github.com/GameServerManagers/LinuxGSM/raw/develop/Factorio/fctrserver) rather than from master.

2. Change the line `branch="stable"` to `branch="experimental"`.

3. Change the line `githubbranch="master"` to `githubbranch="develop"`. Once this gets released into master you can switch it back if you want.

4. Configure and run everything else [as you would normally](gameservermanagers.com/lgsm/fctrserver/).

**Comment by Digital-Storm** [comment]
@ClaytonSmith As @wizpig64 said, though do note, that gibb made a change to the variable from updatebranch to branch, so you may need to modify the lgsm/functions/factorio_update.sh script, and replace "updatebranch" with "branch". Do a search in that file for "updatebranch" and change it to "branch" and you should be all set until he merges my patch.

**Comment by wizpig64** [comment]
good catch @Digital-Storm, thanks.

**Comment by ClaytonSmith** [comment]
Good to know, thanks. 

Just a side note. I feel it would be a bit cleaner to be able to specifying the target branch or a specific release number through command line argument, `./fctrserver update x.x.x` or `./fctrserver update experimental`.

**Comment by Maygus** [comment]
@wizpig64 the dev branch link isn't working?

**Comment by Maygus** [comment]
I found - looks like you're changing how the installer first downloads. However...

I cannot find the `branch="stable"` entry you mention... nor any reference to `updatebranch="xxxx"` will this still work?

**Comment by Digital-Storm** [comment]
@Maygus You will need to download and overwrite your original ./fctrserver script with the development branch version, as doing a ./fctrserver update with the development branch selected, will not update the ./fctrserver script itself. 

Perhaps that is something we can get included in the update script.

**Comment by Maygus** [comment]
Thanks - yeah I figured it out after digging around. Had to download lgsm.sh and run that which pulls down the factorio script (when selected) and then digging in it found where I add the entra for experimental so that the factorio script can look at latest experimental. :)

**Comment by XGhozt00** [comment]
Does this still work? I have:

`branch="experimental"`

Inside: `./lgsm/config-lgsm/fctrserver/fctrserver.cfg`

It's using the port and rconpassword variables correctly from that file, but I can't get `./fctrserver update` to install the latest experimental version?

**Pull request merged**
