### PR TITLE
fixes and improved backup

### LINKED ISSUE #1098: backupsdays backup autoclear
It won't be very hard to implement and will allow people to run it as a cronjob.
We can use this as a template : https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/logs.sh#L49

Must-have would be to check if a backup is already pending before starting another, in case somebody messes up and runs the cronjob every minute instead of every day for example. 

Settings the amount of backups to keep would be added to the main script with a backupdays variable, and a value of "0" would mean "infinite". 

I'll probably code a bit in the next days or weeks, so i'm assigning myself.

### PR DESCRIPTION
**Pull request by UltimateByte**
I'm satisfied from my tests, requires some double check & testing and it'll be fine.

Fixes
#1098
#1142
#1141
#1140
#1137
edit: and #1143

### CODE REVIEW

**Comment by dgibbs64** [comment]
Is this backwards compatible?
```
maxbackups="4"
maxbackupdays="30"
stoponbackup="on"
```
Ensure that these commands have a default should they be missing. lookin core_functions.sh under 

```
## Code/functions for legacy servers
```

**Comment by UltimateByte** [comment]
@dgibbs64 If variables don't exist, there is no default values set to not annoy people that don't want backup autoclear, so the backup rotation will just not happen.
That's why i start with `if [ -n "${maxbackupdays}" ]&&[ -n "${maxbackups}" ]; then` to make sure that the process will go flawlessly.

Last commit should fix #1143 please test on ubuntu to confirm.

**Comment by dgibbs64** [comment]
@UltimateByte 

Its looking good so far. Im just looking at your code to make sure I understand it. Came across this error though.
```
[  OK  ] Backup jc2-server: Backup created: jc2-server-2016-10-22-152343.tar.gz is 30M size
find: invalid argument `+' to `-mtime'
```

**Comment by UltimateByte** [comment]
@dgibbs64 Ubuntu ? 😷 
Don't have this issue. o_O
I guess i should move -type f before -mtime to solve this on ubuntu

**Comment by UltimateByte** [comment]
Is it solved now ?

**Comment by dgibbs64** [comment]
Yup fixed

**Comment by dgibbs64** [comment]
A small change. The backup vars should not be listed under advanced vars since we want the user to feel comfortable to change them. Like so.

https://gist.github.com/dgibbs64/a2bc9226763b4112482ee19ff7d070c7

Also the wiki page will need to be updated to users know what exactly they are doing with eh new backup system

**Comment by UltimateByte** [comment]
@dgibbs64 I'll update the wiki after merge.
logdays should come close to backups as well then, what do you think ?

**Pull request merged**
