### PR TITLE
Add proxy support for Telegram alerts via curl

### PR DESCRIPTION
**Pull request by lazymind**
I'm add a simple curl custom string for use curl with proxy in countries like Russia where Telegram has blocked.

### CODE REVIEW

**Comment by UltimateByte** [comment]
Just saw your other PR.
No problem adding this.
Just gotta be added for other game servers as well.

**Comment by lazymind** [comment]
sorry I'm realy new on GitHub dev, it's my first try. I use only TS3Server, but i can add this tips to all game servers without any problems if you want, or, can you tell me, how i can add anything in all game servers cfg at one time?

**Comment by lazymind** [comment]
and sorry for my English, it's not so good. I'm from Russia.

**Comment by UltimateByte** [comment]
No problem, that's cool you're trying it in the first place, this is a good idea to add. 

I personally edit all files by hand when I'm doing this kind of things, that's longer but may main PC is on Windows so...
To add everything at once, you would need to work in Linux directly, you could pull the repo, edit all files for example using the sed command, then push back the changes to your repo lazymind:patch-1.

By the way, if you edit lazymind:patch-1, the new commits will be added to this pull-request. That is why you don't need to make two pull-requests.

**Comment by lazymind** [comment]
ok, nice. 
This PR i made from web browser ))) So, i think it was a cause why i have a 2 PR.
I have a linux laptop on my work. i will try to do this tomorrow (because now 23:36 in Russia, and I realy need to go sleep).
Thank you very much for your help, it's very importatn for guys like me, who try do somthing on GitHub at first time.

Have a nice time, and see you later.

**Comment by lazymind** [comment]
And... it so happened that i can't sleep with some not compleated jobs...
So, i figured out with GitHub structure, and make necessary changes in all Games cfg's.
Now i think i can go to sleep and wait for confirmation or remarks to my changes.

Have a nice time 2 all.

**Comment by UltimateByte** [comment]
Haha, welcome to the club of people who can't sleep while something is pending! :p Not the best club though. ^^

Thanks for your work. I'll let @dgibbs64 check and merge this.
Just to let you know, only hotfixes are supposed to be PRed and merged directly into Master. Features should be added to the develop branch first. Though I'm pretty sure @dgibbs64 will be able to deal with it and commit to develop first, we will let you know if needed.

CF this: https://github.com/GameServerManagers/LinuxGSM/wiki/Branching
Don't hesitate reading the Developer section from the Wiki if you ever wish to get more involved into LinuxGSM developping. You can also ask on our Discord's developer section if you have any question.

Cheers :beers:

**Comment by dgibbs64** [comment]
@lazymind looking good. Thank you! Merging to develop

**Pull request merged**
