### PR TITLE
feat: More Gmod addons utilising the installer

### LINKED ISSUE #3402: More installable addons for Garry's mod
Issues raised here are **ONLY** for:
* Feature suggestions.

## User Story

As a as server administrator and developer, I want more addons that can be installed in the linux system autoatically.

## Basic info

* **Distro:** [Ubuntu 20.04]
* **Game:** [Garry's Mod]
* **Command:** [Monitor]
* **LinuxGSM version:** *Last*

## Further Information

Extend the list of the Garry's mod addons list

## Further Reading

https://github.com/GameServerManagers/LinuxGSM/pull/3401

### PR DESCRIPTION
**Pull request by dvdvideo1234**
# Description

Please include a summary of the change and which issues are fixed.

Fixes #3402

## Type of change

* [ ] Bug fix (a change which fixes an issue).
* [x] New feature (change which adds functionality).
* [ ] New Server (new server added).
* [ ] Refactor (restructures existing code).
* [ ] Comment update (typo, spelling, explanation, examples, etc).

## Checklist

PR will not be merged until all steps are complete.

* [x] This pull request links to an issue.
* [x] This pull request uses the `develop` branch as its base.
* [x] This pull request Subject follows the Conventional Commits standard.
* [x] This code follows the style guidelines of this project.
* [x] I have performed a self-review of my code.
* [x] I have checked that this code is commented where required.
* [x] I have provided a detailed with enough description of this PR.
* [x] I have checked If documentation needs updating.

## Documentation

If documentation does need updating either update it by creating a PR (preferred) or request a documentation update.
* User docs: https://github.com/GameServerManagers/LinuxGSM-Docs
* Dev docs: https://github.com/GameServerManagers/LinuxGSM-Dev-Docs

**Thank you for your Pull Request!**

### CODE REVIEW

**Comment by dvdvideo1234** [comment]
Generated by: https://github.com/dvdvideo1234/ZeroBraineProjects/blob/master/GmodLinuxGSMM/main.lua

**Comment by UltimateByte** [comment]
Looking great! Nice thing to have more mods added, thank you for the addition.

**Comment by dvdvideo1234** [comment]
@UltimateByte when exactly this is going to be merged ? Is it going to be soon ?

**Comment by dvdvideo1234** [comment]
Hello, @dgibbs64 

I wonder when PRs are being merged though ... This stayed here for considerate amount of time :+1:

**Comment by dgibbs64** [comment]
It is planned for the next release. I have been very busy recently so haven't had time I normally have to work on LinuxGSM

**Pull request merged**
