### PR TITLE
Use /proc/meminfo instead of free -m

### LINKED ISSUE #1970: Non-English locale in Arch Linux
**Describe the bug**
When I run `./rustserver start` it displays the following error message:

    [ .... ] Starting rustserver: RustWarning! Arch Linux dependency checking unavailable
    [ WARN ] Starting rustserver: Default RCON Password detected!
     * Having CHANGE_ME as a password is not very safe.
    [ INFO ] Starting rustserver: Check IP: 192.168.148.47
    /home/max/Downloads/LinuxGSM-180718.2/lgsm/functions/check_system_requirements.sh: Zeile 37: [: : Ganzzahliger Ausdruck erwartet.
    [  OK  ] Starting rustserver: Rust
I don't know if this is a serious issue, but it's an error message that prohibits the rest of the script from running. The error message is in german, because my locale is `de_DE`. I tried using `en_US` as a locale to generate the error message but then it doesn't appear. This is due to [this line](https://github.com/GameServerManagers/LinuxGSM/blob/070bd4042d684a86ae011c9e927c94c55278634e/lgsm/functions/info_distro.sh#L103) because the command `free -m` has a different output depending on the locale:

    $ LANG=en_US free -m
                  total        used        free      shared  buff/cache   available
    Mem:          15987       10988         985         284        4013        5434
    Swap:         11867          72       11795
    $ LANG=de_DE free -m
                  gesamt       benutzt     frei      gemns.  Puffer/Cache verfügbar
    Speicher:       15987       10951        1020         284        4015        5472
    Swap:         11867          72       11795
Instead you could use:

    $ echo "$(($(grep MemTotal /proc/meminfo | awk '{print $2}')/1024))"
    15987
which works under german as well as english and should work under every distro.

**To Reproduce**
Steps to reproduce the behaviour:

    $ ./rustserver install && LANG=de_DE ./rustserver start

**Expected behaviour**
Less error messages.

### PR DESCRIPTION
**Pull request by MaxMatti**
Fixes #1970.

Also uses numfmt which is included in coreutils since version 8.24. _Edit: 8.21_
Ubuntu has this coreutils version since 16.04 _Edit: 14.04_ (https://packages.ubuntu.com/search?keywords=coreutils)
Debian has this coreutils version since 9 (stretch) _Edit: 8 (jessie)_ (https://packages.debian.org/search?keywords=coreutils)
Unfortunately I could neither find out which version of Fedora is necessary nor which other tool one can use to generate human-readable output from the number that we read from /proc/meminfo (which is in kB).

### CODE REVIEW

**Comment by dgibbs64** [comment]
Thanks. Do you know is the comparability for centos?

**Comment by MaxMatti** [comment]
I don't know any exact details but I just fired up a CentOS 7 VM and that has coreutils 8.22.

**Comment by MaxMatti** [comment]
Seems like is was misinformed. coreutils 8.21 is required. This is present in CentOS 7, Debian 8 and Ubuntu 14.04.

**Comment by UltimateByte** [comment]
On a 16GB RAM Debian 9 machine:

```
root@gaben:~# free -h
              total        used        free      shared  buff/cache   available
Mem:            15G        7.1G        215M        156M        8.0G        7.7G
Swap:           31G        2.1G         29G

root@gaben:~# numfmt --to=iec --from=iec --suffix=B "$(grep ^MemTotal /proc/meminfo | awk '{print $2}')"
16MB
root@gaben:~# numfmt --to=iec --from=iec --suffix=B "$(grep ^MemFree /proc/meminfo | awk '{print $2}')K"
171MB
root@gaben:~# numfmt --to=iec --from=iec --suffix=B "$(($(grep ^MemTotal /proc/meminfo | awk '{print $2}')-$(grep ^MemFree /proc/meminfo | awk '{print $2}')))K"
16GB
```

Not as universal as expected unfortunately.

**Comment by MaxMatti** [comment]
@UltimateByte from which line in the PR did you copy your first line? There's a K missing at the end. Easier to see when you compare it to the other two lines. But I don't find the missing K in the PR.

What this essentially doing is taking the number (that is in kilobytes) and converting it using numfmt. But numfmt needs to know, that the input is kB instead of B, so it needs the K to indicate that.

**Comment by MaxMatti** [comment]
Oops, got it, sorry about that.

**Comment by dgibbs64** [comment]
@MaxMatti is this PR ready to merge?

**Comment by UltimateByte** [comment]
My bad as well, I don't know much of this syntax and thought the "K" was cosmetics while copy/pasting.

It works as intended in Debian 9 currently:

```
root@gaben:~# free -h
              total        used        free      shared  buff/cache   available
Mem:            15G        8.0G        156M        165M        7.2G        6.9G
Swap:           31G        2.0G         30G
root@gaben:~# numfmt --to=iec --from=iec --suffix=B "$(grep ^MemTotal /proc/meminfo | awk '{print $2}')K"
16GB
root@gaben:~# numfmt --to=iec --from=iec --suffix=B "$(grep ^MemFree /proc/meminfo | awk '{print $2}')K"
277MB
root@gaben:~# numfmt --to=iec --from=iec --suffix=B "$(($(grep "^MemTotal\:" /proc/meminfo | awk '{print $2}')-$(grep "^MemFree\:" /proc/meminfo | awk '{print $2}')-$(grep "^Buffers\:" /proc/meminfo | awk '{print $2}')-$(grep "^Cached\:" /proc/meminfo | awk '{print $2}')-$(grep "^SReclaimable\:" /proc/meminfo | awk '{print $2}')))K"
8.0GB

```

Works on CentOS 7 as well:

```
[root@webmastered ~]# free -h
              total        used        free      shared  buff/cache   available
Mem:           3.7G        1.4G        279M        373M        2.0G        1.6G
Swap:          2.0G        219M        1.8G
[root@webmastered ~]# numfmt --to=iec --from=iec --suffix=B "$(grep ^MemTotal /proc/meminfo | awk '{print $2}')K"
3.8GB
[root@webmastered ~]# numfmt --to=iec --from=iec --suffix=B "$(grep ^MemFree /proc/meminfo | awk '{print $2}')K"
327MB
[root@webmastered ~]# numfmt --to=iec --from=iec --suffix=B "$(($(grep "^MemTotal\:" /proc/meminfo | awk '{print $2}')-$(grep "^MemFree\:" /proc/meminfo | awk '{print $2}')-$(grep "^Buffers\:" /proc/meminfo | awk '{print $2}')-$(grep "^Cached\:" /proc/meminfo | awk '{print $2}')-$(grep "^SReclaimable\:" /proc/meminfo | awk '{print $2}')))K"
```

We could leave it there it would be just fine.

The only thing I could see improved is that free is not that useful in this case, free + buff/cache like we tried to get before would made more sense. If there is any chance you can get this it would be awesome.

**Comment by MaxMatti** [comment]
@UltimateByte I could implement that. Should I do that in this PR or open a new one so you can merge this one first?

**Comment by MaxMatti** [comment]
@UltimateByte I hope this is what you meant. If not please give me a calculation showing what you meant.
Now:

    physmemtotal = MemTotal
    physmemfree = MemFree + Buffers + Cached + SReclaimable
    physmemused = MemTotal - MemFree - Buffers - Cached - SReclaimable
this means that `physmemtotal = physmemfree + physmemused`.

@dgibbs64 yes, now this PR is ready to merge. Sorry for the delayed response.

**Comment by UltimateByte** [comment]
> Sorry for the delayed response.
Don't be sorry, we are very grateful for your contribution!

I don't know what SReclaimable is but your calculation sounds great. If you're satisfied with the results, we can call it a go!
We shall do some testing on various distro before merging to master (we merge to develop first unless it's a hotfix) anyways, so don't worry too much. :)

**Comment by MaxMatti** [comment]
Ok.

SReclaimable (I had looked this up while coding it) is "Part of Slab, that might be reclaimed, such as caches" according to `man 5 proc`. [Slab allocation](https://en.wikipedia.org/wiki/Slab_allocation) is a memory management mechanism that is used for kernel objects and eliminates fragmentation.

**Comment by UltimateByte** [comment]
That's not bad. 

I've tested it, it just seems to overestimate free RAM a bit, but it's close on both of my servers.

```
root@gaben:~# numfmt --to=iec --from=iec --suffix=B "$(($(grep ^MemFree /proc/meminfo | awk '{print $2}')+$(grep "^Buffers\:" /proc/meminfo | awk '{print $2}')+$(grep "^Cached\:" /proc/meminfo | awk '{print $2}')+$(grep "^SReclaimable\:" /proc/meminfo | awk '{print $2}')))K" && free -h
4.0GB
              total        used        free      shared  buff/cache   available
Mem:            15G         11G        172M        155M        3.8G        3.5G
Swap:           31G        1.8G         30G
```

**Comment by MaxMatti** [comment]
@UltimateByte in that case I understood your request incorrectly. `total` and `used` are the same as in `free -h` and `free` is `total` minus `used`. I can revert it so that `free` is the same as in `free -h` but I thought that's not what you wanted.

**Comment by UltimateByte** [comment]
OK, I'll try to watch my words and give a proper definition of everything so that we are sure to understand each other!

In the `free` command:
- `total` RAM is the physical total installed RAM
- in older distro, `used` RAM is RAM allocated to processes + buffer/cache
- in newer distro, `used` RAM is only RAM allocated to running processes which makes more sense because most buffer/cache memory can be claimed by processes
- `free` RAM is RAM that is not allocated at all
- `available` RAM is the RAM you can allocate to new or existing processes

In our case, `physmemfree` variable should be equal to actually available RAM in the sense of RAM that can be allocated to processes. This is not exactly equal to `total - used` RAM, because some of the buffer/cache cannot be allocated to processes. 

I examined the output of `/proc/meminfo` and found that the third line, for `MemAvailable` is what we are looking for. This value was present in 3 of my machines: Debian 8, Debian 9, and CentOS 7 so it seems like it is kind of universal.

All that, to say, in the end, the solution is likely to be the following:  
```bash
physmemfree=$(numfmt --to=iec --from=iec --suffix=B "$(grep ^MemAvailable /proc/meminfo | awk '{print $2}')K")
```

**Comment by dgibbs64** [comment]
Just to confirm again ok to merge?

**Comment by UltimateByte** [comment]
With the change I proposed added it should be fine :)

**Comment by dgibbs64** [comment]
OK whenever ready just give me the word and I will merge :)

**Comment by UltimateByte** [comment]
If you have a chance to add my suggestion upper, then it's ready.

https://github.com/GameServerManagers/LinuxGSM/pull/1971/files#diff-4101fe6fe2424e94b74581a82a5c6511R97

Should be: `physmemfree=$(numfmt --to=iec --from=iec --suffix=B "$(grep ^MemAvailable /proc/meminfo | awk '{print $2}')K")`

**Comment by dgibbs64** [comment]
@MaxMatti thanks for your efforts with this really helped out the project!

**Pull request merged**
