### PR TITLE
if backupdir is symlink fix

### PR DESCRIPTION
**Pull request by PhilPhonic**
# Description

If backupdir is a symlink no backups were found.

## Type of change

* [X] Bug fix (a change which fixes an issue).
* [ ] New feature (change which adds functionality).
* [ ] New Server (new server added).
* [ ] Refactor (restructures existing code).
* [ ] Comment update (typo, spelling, explanation, examples, etc).

## Checklist

PR will not be merged until all steps are complete.

* [ ] This pull request links to an issue.
* [X] This pull request uses the `develop` branch as its base.
* [ ] This pull request Subject follows the Conventional Commits standard.
* [ ] This code follows the style guidelines of this project.
* [X] I have performed a self-review of my code.
* [ ] I have checked that this code is commented where required.
* [ ] I have provided a detailed with enough description of this PR.
* [ ] I have checked If documentation needs updating.

## Documentation

If documentation does need updating either update it by creating a PR (preferred) or request a documentation update.
* User docs: https://github.com/GameServerManagers/LinuxGSM-Docs
* Dev docs: https://github.com/GameServerManagers/LinuxGSM-Dev-Docs

**Thank you for your Pull Request!**

### CODE REVIEW

**Comment by PhilPhonic** [comment]
I know "PR will not be merged until all steps are complete" but all those steps don't make sense for this minor change.
I think it's irrelevant to (for example) create an issue for that.

**Comment by JimTR** [comment]
what do you expect ?

**Comment by PhilPhonic** [comment]
I would hope this minor fix gets accepted and merged. If not, I'll work with my own fork. I'm not gonna make big work for this minor change.

**Comment by JimTR** [comment]
I would work on your own fork .. I do with the web version I am coding .. nuff said perhaps

**Comment by PhilPhonic** [comment]
kbye

**Pull request closed without merging**
