### PR TITLE
Discord alert: Allow public_ ip and port overrides

### PR DESCRIPTION
**Pull request by robobenklein**
https://github.com/GameServerManagers/LinuxGSM/issues/1664

### CODE REVIEW

**Comment by UltimateByte** [comment]
Good idea, but it won't work if public IP is an IPv6, as it currently occurs when ipv6 is available.

**Comment by robobenklein** [comment]
@UltimateByte Can you explain further? Perhaps give an example?

This doesn't introduce any new bugs as far as I'm aware, it just gives another option for resolving a case in which the IP field of the notification is wrong.

**Comment by UltimateByte** [comment]
Quick example : 

````bash
root@gaben:~# public_ip="10:AB:24"; ip="127.0.0.1"; value="${public_ip:-ip}"; echo "$value"
10:AB:24
````

Well in my case ( https://hastebin.com/osefopepay ) it would try to query the game server on ipv6, which isn't supported.

I'm not saying your code is bad, but in order to not introduce a bug, you would need to check if the public IP is an IPv6 or not. 

Since I don't think any game server supports IPv6, or at least not many as of now, the best solution would be to correct the IP checking system to show only public IPv4.

**Comment by robobenklein** [comment]
This change *only* modifies the IP given through a Discord notification, it doesn't change anything about how LGSM queries a server or binds to an IP. You could set this `$public_ip` to literally anything you want and it wouldn't affect your use case at all unless you were using Discord alerts.

Here the `$public_ip` is not going to be used in LGSM at all, it's purely for humans to see.

For example, I plan to set mine to something akin to `tf2ware.robosane.net` which isn't an IP at all. I could even set `public_ip="lolsomething that's not an ip"` and the only problem would be that the GameTracker.com URL in the Discord notif wouldn't work...

**Comment by robobenklein** [comment]
Actually @UltimateByte you just helped me realize how confusing this is calling it `public_ip`. I'm gonna redo the discord notification thing to make it much easier and simpler to configure.

**Pull request closed without merging**
