### PR TITLE
Minecraft fix for improper default executable

### PR DESCRIPTION
**Pull request by ChaosMTA**
I have no idea how this was not noticed before.
Without this change the following will happen:
[ FAIL ] Starting mc-server: Executable java -Xmx1024M -jar minecraft_server.jar was not found

### CODE REVIEW

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/blob/develop/lgsm/functions/check_executable.sh#L11

`if [ ! -f "${executabledir}/${execname}" ]; then`  
Would expand to something like:  
`"/home/minecraft/serverfiles/java -Xmx1024M -jar /home/minecraft/serverfiles/minecraft_server.jar"`

Would it work with the first part of the expand being totally wrong?

**Comment by ChaosMTA** [comment]
Interesting. I'm not sure why that check doesn't work right now without the filesdir line I added.

**Comment by UltimateByte** [comment]
We should add the full path of the non found executable error message.

**Comment by ChaosMTA** [comment]
What do you mean @UltimateByte

**Comment by UltimateByte** [comment]
Well, the non found executable error message that i made just shows the not found file's name. It should tell the full path. I'm still concerced about my first message though, i'll have a look if needed  Sleeping a bit for now :)

**Comment by UltimateByte** [comment]
Fixed #1285

**Pull request merged**
