### PR TITLE
add send command to console

### LINKED ISSUE #1917: Send command to console
Hi and thanks for this amazing tool :)

i would to know if this was possible to add a command to send command directly to the console like that
`./gameserver command "cmd to run in the console"`

i'm making a server manager and want to interact with each server without connection to the console

thanks :)

### PR DESCRIPTION
**Pull request by DUDU54**
Added a function to send command directly to the console
If the user don't provide a command right after the "send" argument, he will be prompt to enter a command

Fixes #1917 #2334

## Type of change

* [ ] Bug fix (change which fixes an issue).
* [X] New feature (change which adds functionality).
* [ ] New Server (new server added).
* [ ] Refactor (restructures existing code).
* [ ] Comment update (typo, spelling, explanation, examples, etc).
* [x] This change requires a documentation update.

## Checklist

* [X] This code follows the style guidelines of this project.
* [X] This pull request links to an issue.
* [X] This pull request uses the `develop` branch as its base.
* [X] I have performed a self-review of my own code.
* [ ] I have squashed commits.
* [ ] I have commented my code, particularly in hard to understand areas.
* [ ] I have made corresponding changes to the documentation if required.

## Provide Github Email

```
Co-authored-by: DUDU54 <14166148+DUDU54@users.noreply.github.com>
```

### CODE REVIEW

**Comment by dgibbs64** [comment]
Amazing the support this project is getting from people! There are so many features I simply don't have time to develop and others are taking it upon themselves to help out. Thank you!

**Comment by Frisasky** [comment]
link issue #2334

**Comment by dgibbs64** [comment]
This command should only be made available to compatible servers

**Comment by ricksterhd123** [comment]
Will this have support in multi theft auto? I think this feature would be great.

**Comment by ricksterhd123** [comment]
This is a perfect feature but no one is active to approve it :(

**Comment by vinanrra** [comment]
This will be awesome to add, because with Docker container you will be able to show the info at logs

**Comment by ricksterhd123** [comment]
> This will be awesome to add, because with Docker container you will be able to show the info at logs
Indeed, it would be very convenient - hopefully it gets merged soon, I kinda ought to test it for myself.
@dgibbs64 What's the ETA for this?

**Comment by dgibbs64** [comment]
Just an update on this. Once issue #2844 is complete I will be able to merge this as it will allow this command to only show with servers that are compatible with it.

**Comment by dgibbs64** [comment]
@DUDU54 got there in the end. The send command will be part of the next release. Thank you for your contribution ❤️

**Pull request merged**
