### PR TITLE
feat(mods): add rust carbon mod

### LINKED ISSUE #4121: [Feature]: add Carbon mod to mods list
### User story

As a developer I would like to add support for Carbon mod

### Game

Rust

### Linux distro

_No response_

### Command

command: mods-install

### Further information

https://carbonmod.gg/

### PR DESCRIPTION
**Pull request by dgibbs64**
# Description

Add support for carbon mod

Fixes #4121

## Type of change

-   [ ] Bug fix (a change which fixes an issue).
-   [x] New feature (a change which adds functionality).
-   [ ] New Server (new server added).
-   [ ] Refactor (restructures existing code).
-   [ ] Comment update (typo, spelling, explanation, examples, etc).

## Checklist

PR will not be merged until all steps are complete.

-   [x] This pull request links to an issue.
-   [x] This pull request uses the `develop` branch as its base.
-   [x] This pull request subject follows the Conventional Commits standard.
-   [x] This code follows the style guidelines of this project.
-   [x] I have performed a self-review of my code.
-   [x] I have checked that this code is commented where required.
-   [x] I have provided a detailed enough description of this PR.
-   [x] I have checked if documentation needs updating.

## Documentation

If documentation does need updating either update it by creating a PR (preferred) or request a documentation update.

-   User docs: https://github.com/GameServerManagers/LinuxGSM-Docs
-   Dev docs: https://github.com/GameServerManagers/LinuxGSM-Dev-Docs

**Thank you for your Pull Request!**

### CODE REVIEW

**Comment by h3o66** [comment]
As written in the Carbonmod support forum post:

I would enable the following if it is installed via lgsm
```
preexecutable='LD_PRELOAD="libdoorstop.so"'
export DOORSTOP_ENABLED=1
export DOORSTOP_TARGET_ASSEMBLY="${serverfiles}/carbon/managed/Carbon.Preloader.dll"
```

corrected with the new assembly lib

**Comment by dgibbs64** [comment]
environment.sh does this and is triggered if it exists

**Comment by h3o66** [comment]
the difference is that all executeables preload now this lib for all executeables at the start.

another point:
probably the production tag would be better instead of the latest release as well:
https://github.com/CarbonCommunity/Carbon.Core/releases/tag/production_build

the direct download here should be probably enough:
https://github.com/CarbonCommunity/Carbon.Core/releases/download/production_build/Carbon.Linux.Release.tar.gz

**Comment by jbrazio** [comment]
I'm a core developer of Carbon.

For long term maintenance reasons I think it's better to source the `environment.sh` (as it is already done by this PR) instead of issuing all the environment preparation commands on the linuxgsm script itself.

We also recommend using the `production_build` tag as this is the most stable channel.
This PR needs to update the archive name to ` Carbon.Linux.Release.tar.gz`.

@dgibbs64 when should we expect for the PR to be merged ? Thanks.
If you need any support don't hesitate to contact us.

**Comment by dgibbs64** [comment]
If the only update is the name change I can get it merged very soon. Carbon is planned for the next release.

**Comment by dgibbs64** [comment]
@jbrazio can you give this anther look and I will approve the merge if happy :)

**Comment by jbrazio** [comment]
Just to be sure all is fine what is the easiest way to test the version on from this PR locally on my system ?

**Comment by jbrazio** [comment]
@dgibbs64 Just to be sure all is fine what is the easiest way to test the version from this PR locally on my system ?

**Comment by dgibbs64** [comment]
you can edit `rustserver` on this line https://github.com/GameServerManagers/LinuxGSM/blob/master/linuxgsm.sh#L52 to use the branch instead and run `./rustserver ul`

**Comment by jbrazio** [comment]
@dgibbs64 As soon as I run `./rustserver mods-install` I get the following error `parse error: Invalid numeric literal at line 2, column 0`. The mod is not working I think it's because you are executing the environment script instead of sourcing it. I left a comment on the code.

**Comment by dgibbs64** [comment]
whats the easiest way to confirm carbon is working?

**Comment by jbrazio** [comment]
You need to launch it attached to the console (debug) because this happens very early on the boot process. But if carbon is loaded there is an ascii banner showing. You can also check the folder `carbon/logs` and find three files there: Preloader, Bootstrap and Core.

**Comment by oddbunchmedia** [comment]
@dgibbs64 - in case you're not aware, the `parse error: Invalid numeric literal at line 2, column 0` is present in the current prod version of LGSM too.

**Comment by jbrazio** [comment]
https://github.com/CarbonCommunity/Carbon.Core/commit/20ff577e6846af4b5f73f1aa149979c4e6bbe6c7
@dgibbs64 with this commit things should work much better. Like I said prev, instead of executing the file just `source` it and all will work fine, before some verbose output of the injector was messing with the stdin and breaking stuff in LinuxGSM.

**Comment by dgibbs64** [comment]
Thanks. I will try it out now as I was having difficulty when testing.

**Comment by dgibbs64** [comment]
I am now happy this is working

**Comment by jbrazio** [comment]
@dgibbs64 when should we expect for this change to be released ?

**Comment by BloodyMikey** [comment]
Is it possible to select the different releases and builds?.
Production
Development
Commit
Staging.

**Pull request merged**
