### PR TITLE
feature(valheim): add support for Valheim Plus mod

### LINKED ISSUE #3287: [FEATURE] Mod Integration Valheim Server
## User Story

I want the LinuxGSM script to be able to start the Unity Mod Container/Wrapper that one can use to add Mods to the server.

Link to the container:
// https://github.com/BepInEx/BepInEx //

Link to a mod that also integrates the correct version of the container

// https://github.com/nxPublic/ValheimPlus //

## Basic info

* **Distro:** [ Debian 4.19.160-2 (2020-11-28) x86_64]
* **Game:** [Valheim]
* **Command:** [./vhserver start]
* **LinuxGSM version:** [v21.1.3]

## Further Information

The above container is basically a standart tool to load mods into unity, this tool can be used to load a various amount of mods and integrate them into the binary via inject.

The binary loads the game server which is obviously not something linuxgsm would allow since GSM is a container in and on itself.
It would be amazing if that would be added since this would change a lot and would lift LinuxGSM apart from any free hoster and maybe more people would not only use LinuxGSM but would also learn to understand how linux works.

## Further Reading

Link to the container:
// https://github.com/BepInEx/BepInEx //

Link to a mod that also integrates the correct version of the container

// https://github.com/nxPublic/ValheimPlus //

### PR DESCRIPTION
**Pull request by h3o66**
# Description

Add Valheim Plus to the Mods

Fixes #3287

## Type of change

* [ ] Bug fix (a change which fixes an issue).
* [x] New feature (change which adds functionality).
* [ ] New Server (new server added).
* [ ] Refactor (restructures existing code).
* [ ] Comment update (typo, spelling, explanation, examples, etc).

## Checklist

PR will not be merged until all steps are complete.

* [x] This pull request links to an issue.
* [x] This pull request uses the `develop` branch as its base.
* [x] This pull request Subject follows the Conventional Commits standard.
* [x] This code follows the style guidelines of this project.
* [x] I have performed a self-review of my code.
* [x] I have checked that this code is commented where required.
* [x] I have provided a detailed with enough description of this PR.
* [ ] I have checked If documentation needs updating.

## Documentation

If documentation does need updating either update it by creating a PR (preferred) or request a documentation update.
* User docs: https://github.com/GameServerManagers/LinuxGSM-Docs
* Dev docs: https://github.com/GameServerManagers/LinuxGSM-Dev-Docs

**Thank you for your Pull Request!**

### CODE REVIEW

**Comment by neckcen** [comment]
It would be cool to offer BepInEx and V+ separately as the former can be used to load many other mods too, not just V+.

**Comment by StudioEtrange** [comment]
> It would be cool to offer BepInEx and V+ separately as the former can be used to load many other mods too, not just V+.

But it seems that BepInEx distributed inside UnixServer.tar.gz (which is the one from https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/) is a special version of BepInEx for V+. 

If i guess right, it might be not possible to use the standard BepInEx version for V+

**Comment by neckcen** [comment]
> But it seems that BepInEx distributed inside UnixServer.tar.gz (which is the one from https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/) is a special version of BepInEx for V+.
> 
> If i guess right, it might be not possible to use the standard BepInEx version for V+

I'm pretty sure you are correct, and that is the version I'd wish to see offered as a stand alone since many mods can then be used (200+ according to the link provided).

**Comment by J-O-S-H-C** [comment]
I've been testing this PR all day and it appears to be working very well. I've run it across three instances (two on one user) of Valheim worlds. I have about six people that have successfully used the mod as clients across those worlds.

**Comment by NotSoSocial** [comment]
Github newb here, how can i use this on my linuxgsm server. what commands do i need to use in order to utilize this new function.,

**Comment by h3o66** [comment]
> Github newb here, how can i use this on my linuxgsm server. what commands do i need to use in order to utilize this new function.,

to use this:
backup the vhserver script `cp vhserver vhserver_bck`

exchange the 2 variables in the vhserver script:
```
githubuser="h3o66"
githubbranch="feature/valheimplus"
```

then just update lgsm:
`./vhserver ul`

then you can use the mod-install command.

**Comment by cyberlimbo** [comment]
> > Github newb here, how can i use this on my linuxgsm server. what commands do i need to use in order to utilize this new function.,
> 
> to use this:
> backup the vhserver script `cp vhserver vhserver_bck`
> 
> exchange the 2 variables in the vhserver script:
> 
> ```
> githubuser="h3o66"
> githubbranch="feature/valheimplus"
> ```
> 
> then just update lgsm:
> `./vhserver ul`
> 
> then you can use the mod-install command.


Hi

We still need to use this or there are other ways to install v+?

Regards

**Comment by h3o66** [comment]
> > > Github newb here, how can i use this on my linuxgsm server. what commands do i need to use in order to utilize this new function.,
> > 
> > 
> > to use this:
> > backup the vhserver script `cp vhserver vhserver_bck`
> > exchange the 2 variables in the vhserver script:
> > ```
> > githubuser="h3o66"
> > githubbranch="feature/valheimplus"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > then just update lgsm:
> > `./vhserver ul`
> > then you can use the mod-install command.
> 
> Hi
> 
> We still need to use this or there are other ways to install v+?
> 
> Regards

This is still needed as the PR is not merged nor in a release of lgsm yet.
Be aware that you update to the latest dev release of lgsm when updating with this method.

**Comment by cyberlimbo** [comment]
yeah, i just installed a new fresh lgsm on my debian machine.
Thank you, i will test it right now ;)

**Comment by cyberlimbo** [comment]
I followed the instruction exactly as described, it installed the v+ with no problems.
I added some simple mods (Valdream-MaxPlayerModifier-1.0.0 and Valdream-Data_Rate_Modifier-1.0.1).
the server started and the mods config was created.

The thing is, the server is now not showing on steam servers list.
What could be the problem?

**Review by dgibbs64 — APPROVED** [review]

**Pull request merged**
