### PR TITLE
feat(config): add secrets config to store sensitive settings

### LINKED ISSUE #1993: Add secrets configuration: `secrets.cfg`
I would like to track my config directory with git, but I'd rather not compromise my Steam credentials which are stored in `common.cfg`.

I propose adding a new file, `secrets.cfg` or similar, in the same directory as `common.cfg`. This new file will get sourced just before common configuration. This would allow adding the secrets file to gitignore.

---

I tried doing this and sourcing the secrets from common.cfg, but my bash-foo isn't good enough (though there is [a way](https://unix.stackexchange.com/a/273348/34451) I haven't tried), and I'm not sure what would happen to it after an LGSM update anyway.

I'm happy to do this myself if the team thinks it's a good idea.

### PR DESCRIPTION
**Pull request by dgibbs64**
# Description

Some LinuxGSM users want a place to store sensitive settings like Steam Credentials that is separated from the main settings. This allows users to track configs in git or equivalent while allowing users to exclude these sensitive configs. This can be useful for a skeleton configuration to apply custom settings and maps etc.

Fixes #1993

## Type of change

* [ ] Bug fix (a change which fixes an issue).
* [x] New feature (change which adds functionality).
* [ ] New Server (new server added).
* [ ] Refactor (restructures existing code).
* [ ] Comment update (typo, spelling, explanation, examples, etc).

## Checklist

PR will not be merged until all steps are complete.

* [x] This pull request links to an issue.
* [x] This pull request uses the `develop` branch as its base.
* [x] This pull request Subject follows the Conventional Commits standard.
* [x] This code follows the style guidelines of this project.
* [x] I have performed a self-review of my code.
* [x] I have checked that this code is commented where required.
* [x] I have provided a detailed with enough description of this PR.
* [x] I have checked If documentation needs updating.

## Documentation

If documentation does need updating either update it by creating a PR (preferred) or request a documentation update.
* User docs: https://github.com/GameServerManagers/LinuxGSM-Docs
* Dev docs: https://github.com/GameServerManagers/LinuxGSM-Dev-Docs

**Thank you for your Pull Request!**

### CODE REVIEW

**Comment by dgibbs64** [comment]
#585 should also be investigated to make it easy to allow users to create a skeleton

**Review by h3o66 — COMMENTED** [review]
Might be good to migrate automatic the steam credentials or other things over to the new config.

`grep -R "^steam" oldconfig.cfg >> secrets.cfg`

And then delete them from the old config:
`sed -i '/^steam/d' oldconfig.cfg`

**Comment by dgibbs64** [comment]
> Might be good to migrate automatic the steam credentials or other things over to the new config.
> 
> `grep -R "^steam" oldconfig.cfg >> secrets.cfg`
> 
> And then delete them from the old config:
> `sed -i '/^steam/d' oldconfig.cfg`

I think that in this case it should be up to the user to move credentials to this config file as this config is optional.

**Comment by dgibbs64** [comment]
I am happy with this. Docs just needs to be updated

**Review by h3o66 — APPROVED** [review]
looks good to me

**Comment by dgibbs64** [comment]
docs added

**Pull request merged**
