### PR TITLE
fix(btserver): add dependency check for libicu

### LINKED ISSUE #3082: Barotrauma server start does not without libicu
## User Story

As a user i want that the 

## Basic info

* **Distro:** [CentOS 8]
* **Game:** [Barotrauma]
* **Command:** [start]
* **LinuxGSM version:** [v20.5.1]

## Further Information

Wtihout the dependency libicu the server does not start and the core is dumped

```
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.GetCultureInfoHelper(Int32, System.String, System.String)
   at System.Globalization.CultureInfo.GetCultureInfo(System.String)
   at System.Reflection.RuntimeAssembly.GetLocale()
   at System.Reflection.RuntimeAssembly.GetName(Boolean)
   at System.Reflection.Assembly.GetName()
   at Barotrauma.GameMain..cctor()
   at Barotrauma.Program.Main(System.String[])
./DedicatedServer.exe: line 1:  5499 Aborted                 (core dumped) ./DedicatedServer
```

## To Reproduce

Steps to reproduce the behaviour:
1. Install on clean centos
2. start server
3. check console log

## Expected behaviour

starts without a crash

### PR DESCRIPTION
**Pull request by h3o66**
# Description

Add the missing dependency libicu for Barotrauma

Fixes #3082

## Type of change

* [x] Bug fix (a change which fixes an issue).
* [ ] New feature (change which adds functionality).
* [ ] New Server (new server added).
* [ ] Refactor (restructures existing code).
* [ ] Comment update (typo, spelling, explanation, examples, etc).

## Checklist

PR will not be merged until all steps are complete.

* [x] This pull request links to an issue.
* [x] This pull request uses the `develop` branch as its base.
* [x] This pull request Subject follows the Conventional Commits standard.
* [x] This code follows the style guidelines of this project.
* [x] I have performed a self-review of my code.
* [x] I have checked that this code is commented where required.
* [x] I have provided a detailed with enough description of this PR.
* [x] I have checked If documentation needs updating.

## Documentation

If documentation does need updating either update it by creating a PR (preferred) or request a documentation update.
* User docs: https://github.com/GameServerManagers/LinuxGSM-Docs
* Dev docs: https://github.com/GameServerManagers/LinuxGSM-Dev-Docs

**Thank you for your Pull Request!**

### CODE REVIEW

**Review by dgibbs64 — COMMENTED** [review]
Just to confirm is this a CentOS only issue?

**Comment by h3o66** [comment]
> Just to confirm is this a CentOS only issue?

Might notbe a only centos issue, but i did not research yet what version is needed for debian, as i to probably spin up a new installation for this.

On debian there It would be probably the `libicu63` package for this.

**Comment by h3o66** [comment]
There are different versions of the lib for the different debian versions:
https://packages.debian.org/search?suite=all&searchon=names&keywords=libicu

**Comment by h3o66** [comment]
Just added the dependency for debian/ubuntu as well

**Pull request merged**
