### PR TITLE
[WIP] feat(newserver) PaperMC

### PR DESCRIPTION
**Pull request by DUDU54**
PaperMC is a Minecraft server fork of spigot (which is a fork of Bukkit) with some improvement and also an API to check when update is needed
It support version selection via the API

Image of Version selector

Tell me if a have missed something when adding new server type to LGSM 

## Type of change

* [ ] Bug fix (change which fixes an issue).
* [ ] New feature (change which adds functionality).
* [X] New Server (new server added).
* [ ] Refactor (restructures existing code).
* [ ] Comment update (typo, spelling, explanation, examples, etc).
* [ ] This change requires a documentation update.

## Checklist

* [X] This code follows the style guidelines of this project.
* [X] This pull request uses the `develop` branch as its base.
* [X] I have performed a self-review of my own code.
* [ ] I have squashed commits.
* [X] I have commented my code, particularly in hard to understand areas.
* [ ] I have made corresponding changes to the documentation if required.

## Provide Github Email

```
Co-authored-by: DUDU54 <14166148+DUDU54@users.noreply.github.com>
```

### CODE REVIEW

**Comment by dgibbs64** [comment]
@DUDU54 you might be a good person to ask. There are so many different "versions" of mincecraft that I have been reluctant to support all but vanilla. Is there an article explaining what the different versions are all about?

**Comment by DUDU54** [comment]
> @DUDU54 you might be a good person to ask. There are so many different "versions" of mincecraft that I have been reluctant to support all but vanilla. Is there an article explaining what the different versions are all about?

@dgibbs64  Here is a good one [What is Spigot? CraftBukkit? Bukkit? Vanilla? Forge? PaperSpigot? Etc.](https://www.spigotmc.org/wiki/what-is-spigot-craftbukkit-bukkit-vanilla-forg/)

**Comment by dgibbs64** [comment]
@DUDU54 thanks. Clear as mud haha. I think because of the complexity of the versions it makes sense for each Minecraft variant to have its own server version.

**Comment by dgibbs64** [comment]
@DUDU54 would it be a good idea to do a version select for vanilla minecraft as well?

**Comment by DUDU54** [comment]
@dgibbs64 Sure,  i will look to do that.

Also, where can i move the selection function which take a string with option on each line to not duplicate the code for each server type

**Comment by dgibbs64** [comment]
core_messages might be a good place as its UI related

**Comment by kyleedwardsny** [comment]
> I think because of the complexity of the versions it makes sense for each Minecraft variant to have its own server version.

This gets even more complicated when you add modpacks into the picture. What is the "version" at that point? Do we add a different server for every modpack in existence?

FWIW, I am using Minecraft with the Sky Factory 4 modpack. To get it to work, I just copied my existing server files into the `serverfiles` directory, and added a symlink `minecraft_server.jar` that just points to the Forge JAR.

**Comment by alx365** [comment]
are there plans to merge this soon? this PR is kind of dead

**Review by h3o66 — CHANGES_REQUESTED** [review]
Please rebase and resolve the conflicts

**Comment by dgibbs64** [comment]
Minecraft is being reviewer by me currently. This PR will be part of that.

**Comment by h3o66** [comment]
closing this in favour of #3292

**Pull request closed without merging**
