### PR TITLE
fix(stop): change csgoserver stop mode

### LINKED ISSUE #2992: [Feature Request] Exitmode: CTRL+C + `quit` command
## User Story

When server source engine's server use `-autoupdate` launch option then it restarting after `quit` or `exit` and this methods fails.
But, if you send CTRL+C before this commands then server closes successfully.

Actual for my little CSGO server. Every restart i'm compelled do in manual mode or wait 30 seconds.

## Basic info

* **Distro:** [Debian 10]
* **Game:** [CSGO]
* **Command:** [stop]
* **LinuxGSM version:** [v20.4.1]

## Further Information

1. Send CTRL+C to server console.
2. Send `quit` to server console.
3. ... You great!

### PR DESCRIPTION
**Pull request by h3o66**
# Description

Changes stop mode to 9 (GoldSrc) to take in to account `-autoupdate` in the arguments.

Fixes #2992

## Type of change

* [ ] Bug fix (a change which fixes an issue).
* [ ] New feature (change which adds functionality).
* [ ] New Server (new server added).
* [x] Refactor (restructures existing code).
* [ ] Comment update (typo, spelling, explanation, examples, etc).

## Checklist

PR will not be merged until all steps are complete.

* [x] This pull request links to an issue.
* [x] This pull request uses the `develop` branch as its base.
* [x] This pull request Subject follows the Conventional Commits standard.
* [x] This code follows the style guidelines of this project.
* [x] I have performed a self-review of my code.
* [x] I have checked that this code is commented where required.
* [x] I have provided a detailed with enough description of this PR.
* [ ] I have checked If documentation needs updating.

## Documentation

If documentation does need updating either update it by creating a PR (preferred) or request a documentation update.
* User docs: https://github.com/GameServerManagers/LinuxGSM-Docs
* Dev docs: https://github.com/GameServerManagers/LinuxGSM-Dev-Docs

**Thank you for your Pull Request!**

### CODE REVIEW

**Comment by dgibbs64** [comment]
subject should be either feat or fix. Refactor is not supported (but wish it was).

**Review by dgibbs64 — CHANGES_REQUESTED** [review]
CS:GO in this instance is acting like many GolgSrc servers in that quit triggers a restart of the server

The solution is to change CS:GO to use `9: GoldSrc` stop option as it sends quit then closes 3 seconds after the quit.

**Comment by TheByKotik** [comment]
> CS:GO in this instance is acting like many GolgSrc servers in that quit triggers a restart of the server
> 
> The solution is to change CS:GO to use `9: GoldSrc` stop option as it sends quit then closes 3 seconds after the quit.

I suppose correct server shutdown better than restart and killing process.

**Comment by dgibbs64** [comment]
@TheByKotik The correct shutdown is quit then ctrl+c. ctrl+c alone is forcing close

**Review by dgibbs64 — APPROVED** [review]

**Comment by TheByKotik** [comment]
> @TheByKotik The correct shutdown is quit then ctrl+c. ctrl+c alone is forcing close

image

CTRL + C will be delayed with `-autoupdate` params.

**Pull request merged**
