### PR TITLE
mod_list Update / Fix

### PR DESCRIPTION
**Pull request by VoxxieBoxxie**
Fixed PAC3 not being in Global Array
Added Wiremod AutoInstaller
Added Wiremod-Extras AutoInstaller

### CODE REVIEW

**Comment by UltimateByte** [comment]
Thanks for this, blame me for the mistake, I forgot to add them to the global array when adding these last three :)

@dgibbs64 I reviewed the code: clean, can merge :)

**Comment by dgibbs64** [comment]
@UltimateByte you happy to release a hotfix?

**Comment by UltimateByte** [comment]
@dgibbs64 Since it's a missing feature fix, i'm OK with having it in develop first. Depends when the next released will be and if you want to train me with hotfixes. :)

**Comment by dgibbs64** [comment]
I was thinking of doing a release this weekend if I get the time :). Since it's not an urgent hotfix is can go in to develop.

**Comment by dgibbs64** [comment]
@VoxxieBoxxie Thanks for your commit!

**Pull request merged**
