### PR TITLE
feat(newserver): Atlas

### PR DESCRIPTION
**Pull request by xtoor**
# Description
[New Feature]
+Added Atlas Server Support
+Added Config Files
+Modified Some Ark files as Copy and renamed as Atlas as they are same base game

[issue]
-They are few non breaking errors in the code that needs review
-Server requires Redis Server to work properly 
-Server requires Map to be edited and placed on the corresponding folder

connects #2158

## Type of change

* [ ] Bug fix (non breaking change which fixes an issue)
* [X] New feature (non breaking change which adds functionality)
* [ ] Refactor (non breaking change restructures existing code)
* [X] This change requires a documentation update

## Checklist

* [X] My code follows the style guidelines of this project
* [x] This pull request links to an issue
* [X] I have performed a self review of my own code
* [ ] I have commented my code, particularly in hard to understand areas
* [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by xtoor** [comment]
[TODO]
-Add REDIS support and/or documentation to setup
-Add MapEditor support and/or documentation to setup
-Include a default preset Map

**Comment by dgibbs64** [comment]
Great work. Will be looking at this as soon as I have free time :)

**Comment by xtoor** [comment]
Ouches! Missed a bunch of details there :/ good thing you’re checking over

**Comment by dgibbs64** [comment]
Looking at this but as usual, this type of server is quite complicated and messy. I am getting core dumps currently.

```
Using binned.
4.5.1-0+UE4 7038 3077 409 10
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 834910
Signal 11 caught.
EngineCrashHandler: Signal=11
/home/lgsm/atlasserver/lgsm/functions/command_debug.sh: line 109:  5227 Segmentation fault      (core dumped) ${executable} ${parms}
```
also the servername var is broken
```
ATLAS Server Details
=======================================================================================================================================================================================================
Server name:                           LastJoinedSessionPerCategory(AtlasId)
LastJoinedSessionPerCategory(AtlasId)
LastJoinedSessionPerCategory(AtlasId)
LastJoinedSessionPerCategory(AtlasId)
LastJoinedSessionPerCategory(AtlasId)
LastJoinedSessionPerCategory(AtlasId)
LastJoinedSessionPerCategory(AtlasId)
LastJoinedSessionPerCategory(AtlasId)
LastJoinedSessionPerCategory(AtlasId)
Server IP:                             1.2.3.4:7777
Admin password:                        CHANGE_ME
Maxplayers:                            70
Default Map:                           Ocean
Status:                                OFFLINE
```

details needs further investigation as well

**Comment by xtoor** [comment]
Yes, if helps I can grab full Configs from my windows install to compare. As well as adding an script to check for redis-Server and exec 
sudo systemctl status redis
Sudo apt install redis-server

**Comment by Carmondai** [comment]
Any update on this?

**Comment by dgibbs64** [comment]
Atlas is a complex server to develop with. Sadly it is taking a while to get it right.

**Comment by Carmondai** [comment]
Guess I'll do some testing after work then (and brush up my shell skills once again)

**Comment by xtoor** [comment]
Any contribution to speed this up is very welcome. I have limited free time and not a lot of knowledge so I’m pretty much doing my best and learning as I go.

**Comment by dgibbs64** [comment]
I re-tested ATLAS and got a libssl error. This server seems to be a little unstable currently

**Pull request merged**
