### PR TITLE
 Update to new stable version of sourcemod

### PR DESCRIPTION
**Pull request by Cripix**
# Description

Update to new stable version of sourcemod
https://forums.alliedmods.net/showthread.php?t=319202

Fixes #[issue]

## Type of change

* [ ] Bug fix (change which fixes an issue).
* [ ] New feature (change which adds functionality).
* [ ] New Server (new server added).
* [x] Refactor (restructures existing code).
* [ ] Comment update (typo, spelling, explanation, examples, etc).

## Checklist

PR will not be merged until all steps are complete.

* [ ] This pull request links to an issue.
* [ ] This pull request uses the `develop` branch as its base.
* [x] This code follows the style guidelines of this project.
* [x] I have performed a self-review of my own code.
* [x] I have checked that this code is commented where required.
* [x] I have provided a detailed enough description of this PR.
* [x] I have checked If documentation needs updating.

## Documentation

If documentation does need updating either update it by creating a PR (preferred) or request a documentation update.
* User docs: https://github.com/GameServerManagers/LinuxGSM-Docs
* Dev docs: https://github.com/GameServerManagers/LinuxGSM-Dev-Docs

**Thank you for your Pull Request!**

### CODE REVIEW

**Comment by dgibbs64** [comment]
needs develop merged into this PR

**Comment by borzaka** [comment]
Be careful with this SourceMod update, as might break many existing plugins/extensions/mods.

I would recommend to make SourceMod main versions pre-selectable before installing/updating:
```
1.9  <--
1.10
```

On a production environment it's very dangerous to update SourceMod 1.9 to 1.10. I'am pretty sure that it would break my setup.

I think if SourceMod already installed, it should only update that branch. 1.9 will still receive gamedata updates. New [1.9 download page](https://www.sourcemod.net/downloads.php?branch=1.9-dev).
And if somebody still wants to upgrade, a new command could be implemented: `mods-upgrade` instead of `mods-update`, or a pre-selection mentioned above.

**Comment by borzaka** [comment]
Well, a [big CS:GO update](https://blog.counter-strike.net/index.php/2019/11/26310/) came out, and SourceMod guys didn't update the gamedata files for the old branch (1.9) as they promised forcing everyone to upgrade to 1.10
I know a way to manually update the 1.9, but that's not easy.

So, the recommended way is to use 1.10, and here is an upgrade guide:
[Upgrading SourceMod](https://wiki.alliedmods.net/Upgrading_SourceMod)

Someone plz check that the LinuxGSM plugin updater follows these update rules.

**Comment by Bara** [comment]
@borzaka A reason is that SM1.9 no longer supported, because SM1.10 is stable. It's open to you to cherry-pick the gamedata commits and push into the 1.9-dev branch and make a pull request. With luck it will be merged, if not then it gives reasonable reasons.

So the most easiest solution is to upgrade SM to 1.10 and it shouldn't break any exist plugin.

**Comment by borzaka** [comment]
Yes, that's exactly what I did. But they stated in their site that there will be gamedata updates:
> The new stable branch of SourceMod is now 1.10. As always, there will be gamedata updates for the old-stable 1.9 branch for a while.

I believed them :)

**Comment by Bara** [comment]
https://github.com/alliedmodders/sourcemod/pull/1129#issuecomment-556985927

I leave this here.

**Pull request closed without merging**
