### PR TITLE
Added ability to send alert on restart command

### LINKED ISSUE #2522: More Alerts for Gameservers
I woud like if the Alert system also supports hand restarts

for example i type ./gmodserver restart and the Discord alert notifies everyone that the server is being restarted if possible.

### PR DESCRIPTION
**Pull request by kennyLtv**
# Description

Adds the ability to enable alerts when a restart is triggered by a server administrator.

Fixes #2522 

## Type of change

* [ ] Bug fix (change which fixes an issue).
* [X] New feature (change which adds functionality).
* [ ] New Server (new server added).
* [ ] Refactor (restructures existing code).
* [ ] Comment update (typo, spelling, explanation, examples, etc).

## Checklist

PR will not be merged until all steps are complete.

* [x] This pull request links to an issue.
* [x] This pull request uses the `develop` branch as its base.
* [x] This code follows the style guidelines of this project.
* [x] I have performed a self-review of my own code.
* [x] I have checked that this code is commented where required.
* [x] I have provided a detailed enough description of this PR.
* [x] I have checked If documentation needs updating.

### CODE REVIEW

**Comment by Frisasky** [comment]
it would be better if alert message are customizable

**Comment by kennyLtv** [comment]
I could see how that would be better.

Right now it's `${servicename} restarted by administrator.`. 

Should we allow them to change the entire string or only the portion following the service name?

**Comment by Frisasky** [comment]
entire string would be better

**Comment by kennyLtv** [comment]
Should be good to go on that change

**Comment by dgibbs64** [comment]
Refactor of alerting done on PR https://github.com/GameServerManagers/LinuxGSM/pull/4345 which now superseeds this PR. Closing

**Pull request closed without merging**
