### PR TITLE
fix(mtaserver): AI no longer waits at a prompt

### LINKED ISSUE #2416: mtaserver autoinstall freezes with prompt
## User Story

MTAserver prompts when attempting to autoinstall - prompts for "Do you want to install MTA default resources? [Y/n] Y"

## Basic info

* Distro: Ubuntu 16.04
* Game: mtaserver (Multi Theft Auto Server)
* Command: ai

## To Reproduce

From a fresh server / new user, attempt to install mtaserver using the command ai. The prompt for:
> Multi Theft Auto Default Resources
>
>Warning! Installing the default resources with existing resources may cause issues.
>Do you want to install MTA default resources? [Y/n] Y

This causes the script to freeze

## Expected behavior
For the script to complete without prompting when using ai

### PR DESCRIPTION
**Pull request by Bourne-ID**
# Description

fix(mtaserver): AI no longer waits at a prompt

Fixes #2416

## Type of change

* [x] Bug fix (change which fixes an issue).
* [ ] New feature (change which adds functionality).
* [ ] New Server (new server added).
* [ ] Refactor (restructures existing code).
* [ ] Comment update (typo, spelling, explanation, examples, etc).

## Checklist

PR will not be merged until all steps are complete.

* [x] This pull request links to an issue.
* [x] This pull request uses the `develop` branch as its base.
* [x] This code follows the style guidelines of this project.
* [x] I have provided Co-author details below.
* [x] I have performed a self-review of my own code.
* [x] I have checked that this code is commented where required.
* [x] I have provided a detailed enough description of this PR.
* [ ] I have checked If documentation needs updating.

## Provide Github Email

Fill out below info or tick box below:
```
Co-authored-by: John Doe <email@example.com>
```

- [ ] I do not wish to provide an email. I am aware this will hide me as the author of this commit.

All pull requests will now be squashed to create a tidy commit history and simplify changelog creation. You can provide either your own email or a GitHub-provided no-reply email.

When a PR is squashed the author becomes the person who squashed the PR. This removes you as the author of your own PR.
The only workaround for this is to add your details as a co-author. More info about co-authors can be found [here](https://help.github.com/en/articles/creating-a-commit-with-multiple-authors).

## Documentation

If documentation does need updating either update it by creating a PR (preferred) or request a documentation update.
* User docs: https://github.com/GameServerManagers/LinuxGSM-Docs
* Dev docs: https://github.com/GameServerManagers/LinuxGSM-Dev-Docs

**Thank you for your Pull Request!**

### CODE REVIEW

**Comment by Bourne-ID** [comment]
Would fix #2416

**Comment by dgibbs64** [comment]
Default resources should be optional. As they are not required in most situations. The user has to download a separate set of files for the specific game mode. So I think it should be off by default. May need a specific command to install default resources.

**Comment by Bourne-ID** [comment]
Easily arranged - I was basing it on the default value during a install run (set to Y).

**Comment by Bourne-ID** [comment]
Quick fix is to default to no on autoinstall - the extra command may be a future feature (that or during the automation script, a user can install the default resources through a different script?)

I'll leave it up to you to decide if you're happy with this PR or would prefer to wait for the extra command.

**Comment by dgibbs64** [comment]
I think this PR should be merged. One solution might be to have a message stating if the user wants to have the default resources to use the normal installer. This will remove the requirement for a whole new command.

**Comment by dgibbs64** [comment]
@Bourne-ID can you please add your email details so I can do a squash merge. Thanks

**Pull request merged**
