### PR TITLE
feat(newserver): add Xonotic

### LINKED ISSUE #3936: [Server Request] Xonotic
## What game server would you like to add?

Xonotic

## Can you link to any tutorials or guides?

Provide any useful documentation or resources that might help.

Official Website:
https://xonotic.org/

Github:
https://github.com/garymoon/xonotic

## Is the server on Steam?

* [ ] Yes
* [x] No

If yes Use SteamDB to get the appid. (https://steamdb.info).

[appid]

## Is the server supported on Linux?

We only support Linux servers and do **not** support Wine.

* [x] Yes
* [ ] No

### PR DESCRIPTION
**Pull request by Hornochs**
# Description

Adding Xonotic as supportes Server

Fixes #3936

## Type of change

-   [ ] Bug fix (a change which fixes an issue).
-   [ ] New feature (a change which adds functionality).
-   [x] New Server (new server added).
-   [ ] Refactor (restructures existing code).
-   [ ] Comment update (typo, spelling, explanation, examples, etc).

## Checklist

PR will not be merged until all steps are complete.

-   [x] This pull request links to an issue.
-   [x] This pull request uses the `develop` branch as its base.
-   [x] This pull request subject follows the Conventional Commits standard.
-   [x] This code follows the style guidelines of this project.
-   [x] I have performed a self-review of my code.
-   [x] I have checked that this code is commented where required.
-   [x] I have provided a detailed enough description of this PR.
-   [x] I have checked if documentation needs updating.

## Documentation

If documentation does need updating either update it by creating a PR (preferred) or request a documentation update.

-   User docs: https://github.com/GameServerManagers/LinuxGSM-Docs
-   Dev docs: https://github.com/GameServerManagers/LinuxGSM-Dev-Docs

**Thank you for your Pull Request!**

### CODE REVIEW

**Comment by Hornochs** [comment]
Any feedback if I need to do something? @dgibbs64 @glowacki-dev @intel44

**Comment by dgibbs64** [comment]
I will take look and review it. Thanks

**Review by dgibbs64 — APPROVED** [review]

**Comment by dgibbs64** [comment]
Completed my review and contributions to get everything up to standard. Non Steam servers normally require some extra work. Thanks for your contirbution

**Comment by Hornochs** [comment]
Thank you very much for your time and effort completing this PR ❤️. I‘m happy that I was able to give a little start and make it possible for LinuxGSM to add this Arenashooter. 

Can‘t wait to install it with LinuxGSM 😊

**Pull request merged**
