### PR TITLE
New core_getop.sh and FastDL generator for all source servers

### PR DESCRIPTION
**Pull request by UltimateByte**
- New core_getopt.sh with no redundant content, as per #1324 and  #1261
- FastDL extended to other source games as per #721
- Default remove non-compressed FastDL files #1322
- Fixed BladeSymphony missing GitHub Info (thanks @cedarlug )

Notes: Please double check and try the new opt on multiple games before final release. We need to make sure that no commands are missing or added while unavailable, even though i spend a lot of time working on it to match previous opt.
This new opt uses a bit more cpu time because of loops and arrays. It should be fine even on slow machines but it's worth testing if you got one available, and it's worth seing if you got ideas to optimize it a bit more, which is why i added 4 reviewers.

Cheers 🍻

### CODE REVIEW

**Comment by UltimateByte** [comment]
**Fixed**
- I noticed dev commands didn't have a core_exit.sh, so I added it.
- core_exit.sh wasn't placed at the right location in core_getopt.sh (my bad), which made the "uf" command display an unnecessary opt after a successful functions update or dev commands.
- Lua enforcer should touch the file before echoing into it.
- Lua enforcer had to look look for non .bz2 files, not the opposite.

**Remaining issues**
- "addons" dir isn't scanned: this is problematic, especially for Garry's Mod.
- For the explanation right below, the directory structure you made will sadly not work for Garry's Mod.

**About Garry's Mod file structure:**

For Garry's Mod, FastDL is more about GUI textures, models, effects, sounds, than maps. Those are either coming from the Workshop (in which case, FastDL won't help), or from addons extracted into `garrysmod/addons/*`
All addons in `addons/<addon_name>` are virtually mounted to `garrysmod` directory, which means that the game acts as if they were extracted to the game directory. The same goes from workshop's .gma files. But they are not actually extracted, and there is a good reason for that: allow to install many addons while keeping all of their files separated, and allow easy addon removal.

Garry's Mod addons can contain any file type, organized in any way that is up to the addon's author. 
It will always contain a `lua` dir for addon's script files, then other dirs might or not use standardized names. Usually, we will find `materials`, `models`, `particles`, `sound`, etc. anyways, which themselves will contain sub-directories, that are sometimes the addon's name (to prevent taking the lead over original game files in the case of duplicate file names) or some more generic names. 

In any case, for the addon to be able to use these files from the FastDL, the original directory structure must be kept. It is unfortunately not as simple as "`*.ext` files in `whatever` dir go to `fastdl/whatever` dir". 

To sum it up: Consider that any file type can be found in any directory, and especially in `addons`. 
So the only way, or at least the easiest to work with Garry's Mod, is to do what I did before: 
1) Scan the whole game directory and copy any file that matches extensions into the "fastdl" dir while keeping the paths structure.
2) Move `fastdl/addons/*/*` to `fastdl`. 
3) Move any remaining darkrpmodification addon stuff in `fastd/lua/"*` to `fastdl`

**Remaining question about Garry's Mod's file structure**

- Is it sometimes useful to keep `fastdl/addons/<addon_name>/*` or should those subdirs always be moved to the `fastdl` dir directly? If they should always be moved, then we can avoid the prompt about it.

**Final thoughts**

As I said once (should have insisted more on that) Garry's Mod is totally different and should have its own FastDL dir build process. Hope that this time, I provided enough details!
I need some sleep atm, but when I wake up, I'll see what I can do to try making a code that achieves this while still using your great additions. Of course, if you wish to work on this before I wake up to make sure we're ready for the release, don't wait for me!

Cheers 🍻

**Comment by UltimateByte** [comment]
`webdir="${lgsmdir}/public_html"` means it won't work with default userdir apache2 mod if user installed his game directly in the user's home dir as suggested.

**Comment by dgibbs64** [comment]
@UltimateByte thanks I didnt know that

**Comment by UltimateByte** [comment]
Your last commit was amazing, it works as it should!

What I've tried so far:
Running a gmod server with ACF addon, built the FastDL, then
- Tried with ACF in my client: Didn't donwload much files
- Tried without ACF in my client: Downloaded all required ACF content.
- Removed the server's lua enforcer, cleaned my client's downloads and tried again: No more FastDL downloads happened.

Works as expected.

Suggestion: 
- Provide less user output while removing or compressing files.

Concern: 
- Maybe files in `addons` dir should be scanned for other Source games to have their addons content downloaded using FastDL.

**Comment by UltimateByte** [comment]
It's all good to me now, except for my little upper concern. :)

**Comment by dgibbs64** [comment]
I can add the addons dir as well for other source engine games. There is no harm in having them there anyway I dont think

**Pull request merged**
