### PR TITLE
fix(vhserver): Add escaped quotes to Valheim startparams to account for spaces

### PR DESCRIPTION
**Pull request by Log1x**
# Description

The current single tick quotes do not work as intended when using spaces in the server name. 

I instead used escaped quotes (tested + working) and added it to the password and world name for sanities sake.

## Type of change

* [x] Bug fix (a change which fixes an issue).
* [ ] New feature (change which adds functionality).
* [ ] New Server (new server added).
* [ ] Refactor (restructures existing code).
* [ ] Comment update (typo, spelling, explanation, examples, etc).

## Checklist

PR will not be merged until all steps are complete.

* [ ] This pull request links to an issue.
* [x] This pull request uses the `develop` branch as its base.
* [x] This pull request Subject follows the Conventional Commits standard.
* [x] This code follows the style guidelines of this project.
* [x] I have performed a self-review of my code.
* [x] I have checked that this code is commented where required.
* [x] I have provided a detailed with enough description of this PR.
* [x] I have checked If documentation needs updating.

### CODE REVIEW

**Comment by dgibbs64** [comment]
Thanks for this. I want to confirm the standards for quoting across LinuxGSM. I am not a fan of the `\"` because I think it can confuse users. However we must of course do what works. This will be considered for a hotfix

**Comment by Log1x** [comment]
> I am not a fan of the \" because I think it can confuse users

Definitely agree. The main thing is using a single `'` in the config file would then require apostrophes to be escaped – it might come down to choosing the lesser evil unless some magic is done behind the scenes.

I've noticed this game in particular seems to be finicky when passing arguments to the executable FWIW.

**Review by dgibbs64 — APPROVED** [review]
yeah, there might need to be some behind the scenes jiggery-pokery to not use `\"` however at least for now this fix will do the job just fine :)

**Comment by dgibbs64** [comment]
@Log1x could you please raise an issue and link it to this PR. Ready to merge once done. Thanks for your help 🚀

**Pull request merged**
