### PR TITLE
feat(new server): pvrserver

### LINKED ISSUE #2382: [Server Request] Pavlov VR Dedicated Server
## What game server would you like adding?
Pavlov VR 
https://store.steampowered.com/app/555160/Pavlov_VR/

The game is built in Unreal Engine.

## Can you link to any tutorials or guides?

Setup guide:
http://wiki.pavlov-vr.com/index.php?title=Dedicated_server

## Is the server on Steam?

* [x] Yes
* [ ] No

[appid]

_Game_
**555160** | Game | **Pavlov VR** | 
[](https://steamdb.info/app/555160/)

_Server_
**622970** | Tool | **Pavlov VR Dedicated Server**
[](https://steamdb.info/app/622970/)

## Is the server supported on Linux?

Yes, server is supported on linux trough SteamCMD

* [x] Yes
* [ ] No

### PR DESCRIPTION
**Pull request by h3o66**
# Description

Please include a summary of the change and which issue is fixed.

Fixes #2382 

## Type of change

* [ ] Bug fix (change which fixes an issue).
* [ ] New feature (change which adds functionality).
* [x] New Server (new server added).
* [ ] Refactor (restructures existing code).
* [ ] Comment update (typo, spelling, explanation, examples, etc).
* [ ] This change requires a documentation update.

## Checklist

* [x] This code follows the style guidelines of this project.
* [x] This pull request links to an issue.
* [x] This pull request uses the `develop` branch as its base.
* [x] I have provided Co-author details below.
* [x] I have performed a self-review of my own code.
* [x] I have squashed commits.
* [ ] I have commented my code, particularly in hard to understand areas.
* [ ] I have made corresponding changes to the documentation if required.

### CODE REVIEW

**Comment by h3o66** [comment]
If someone can please feel free to test this :)

**Comment by h3o66** [comment]
Note for the server:
2 ports are needed in standard it is port 7000 and 7200
port1: value
port2: value +200

**Comment by h3o66** [comment]
Current issue of the Server:
Deletes the content of the Downloaded config after the first start ( Game.ini )
Asked on their discord if they know this issue.

Reference:
https://discordapp.com/channels/267301605882200065/267345481984638986/587743159191077080

**Comment by Frisasky** [comment]
since this server does not supports running multi instances so i think port wont be big problem
beside as far as i know, no other servers utilizing port 7000 and 7200
we can just hard coded the port in config file maybe

**Comment by h3o66** [comment]
> since this server does not supports running multi instances so i think port wont be big problem
> beside as far as i know, no other servers utilizing port 7000 and 7200
> we can just hard coded the port in config file maybe

i dont think multi instances are not possible, but someone who can test this would be good.
The -Port Parameter allows to chnage the port

So i am running 2 instances on the same Server
udp        0      0 0.0.0.0:7000            0.0.0.0:*                           1002       1521889    19552/./PavlovServe 
udp        0      0 0.0.0.0:7001            0.0.0.0:*                           1003       1515026    15972/./PavlovServe 
udp        0      0 0.0.0.0:7200            0.0.0.0:*                           1002       1521883    19552/./PavlovServe 
udp        0      0 0.0.0.0:7201            0.0.0.0:*                           1003       1516587    15972/./PavlovServe 

if this works is another thing, about the wiped config i have no answer for this yet.....

I am not sure if i should remove now the WIP from this because it works except that the game config is wiped by the game at the first start.

**Comment by Frisasky** [comment]
i think we can craft a fix script, start and stop the server once, then download the config file again

**Comment by YannKr** [comment]
Howdy, is there anything I can do to help unblock this PR?

**Comment by Frisasky** [comment]
did a quick testing, it still getting overwritten

**Comment by Frisasky** [comment]
created a rather crude fix, but it worked. feel free to test it
i have removed wip prefix as i think it ready to be shipped

**Comment by Frisasky** [comment]
well found out even with this fix it still overwritten the config file on 2nd startup 
@h3o66 can you asking about the config file problem on their discord again? including this new find

**Comment by dgibbs64** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/LinuxGSM/LinuxGSM/pullRequest?prid=3694988&bid=13018637)

**Comment by h3o66** [comment]
image
conversation on the discord about the config wiping issue.
If nobody minds i will close this

**Comment by Frisasky** [comment]
yeah i agree, if they dont think its a problem at all, we shouldnt care about this game either

**Comment by h3o66** [comment]
So the server is now rebased to the latest lgsm release

**Comment by h3o66** [comment]
To consider to revisit the Server port config:
http://wiki.pavlov-vr.com/index.php?title=Dedicated_server#Advanced_Server_Administration

**Comment by h3o66** [comment]
> To consider to revisit the Server port config:
> http://wiki.pavlov-vr.com/index.php?title=Dedicated_server#Advanced_Server_Administration
> 
> > **[Dedicated server - Pavlov VR Wiki](http://wiki.pavlov-vr.com/index.php?title=Dedicated_server#Advanced_Server_Administration)**

so I revisted a bit the port config according to the docs.

Updated the default port to 7777 and updated the additional port shifting for the server for the details.
(Another port that is needed for the gameserver to be opened)

**Comment by h3o66** [comment]
The inital problem might be solved with the config update via this PR:
GameServerManagers/Game-Server-Configs#105

**Comment by h3o66** [comment]
if someone want to test the current branch from my side for LGSM here is how:

Either create a seperate user for the server or a seperate folder for the server and start there with these commands (Do NOT use the root user !)

```
wget -O linuxgsm.sh https://linuxgsm.sh && chmod +x linuxgsm.sh

sed -i 's/^githubuser=.*/githubuser="h3o66"/g' linuxgsm.sh
sed -i 's/^githubbranch=.*/githubbranch="feature\/pvrserver"/g' linuxgsm.sh

./linuxgsm.sh pvrserver
./pvrserver auto-install
```

The Server can be stoppen and started with
`./pvrserver start`

Stop
`./pvrserver stop`

The intial server config file is in 
`serverfiles/Pavlov/Saved/Config/LinuxServer/Game.ini`

Please give a update if you have tested it and it works now

**Comment by silelmot** [comment]
tested  h3o66s added pavlov-server on 2 pcs and 3 installations and it worked out of the box on arch and debian.

**Comment by h3o66** [comment]
> tested h3o66s added pavlov-server on 2 pcs and 3 installations and it worked out of the box on arch and debian.

Thanks for testing

**Review by dgibbs64 — APPROVED** [review]
Just tested on Ubuntu and works

**Pull request merged**
