### PR TITLE
Teamspeak3 server installation with MariaDB fixed.

### LINKED ISSUE #2260: Teamspeak3 server installation issues with MariaDB
## User Story

If trying to install the TeamSpeak3 server, and use MariaDB as database installation will be successfully completed, but user will not be able to start the server using the MariaDB configured, because generated database connection configuration has syntax error due typo in the installation script, and user is not able to input database socket path in the installation process.

Installation process does not ask user for path to MariaDB socket, which makes the server unable to connect to the database ( at least in my system ), but teamspeak3 server will start successfully. If you fix the ts3db_mariadb.ini after installation and start your server, you will not be able to use the MariaDB.

Configuration file  ( ts3db_mariadb.ini ) generated by the installation process in [install_ts3db.sh](https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/install_ts3db.sh) has issues because typo in the script and i think that user should be able to input the path to the MariaDB socket.

First echo is probably not intentional, and will get written in to the ts3db_mariadb.ini - line 35

```
{
        echo "updating config."
        echo "[config]"
        echo "host='${mariahostname}'"
        echo "port='${mariaport}'"
        echo "username='${mariausername}'"
        echo "password='${mariapassword}'"
        echo "database='${mariadbname}'"
        echo "socket="
} >> "${servercfgdir}/ts3db_mariadb.ini"

```

## Basic info

* Distro: [Centos 7]
* Game: [TeamSpeak3]
* Command: [install]

## Further Information

Issue n.1 typo in [ install_ts3db.sh ](https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/install_ts3db.sh) - line 35 

Issue n.2 [ install_ts3db.sh ](https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/install_ts3db.sh) script does not ask user for database socket path.

Issue n.3 [ install_ts3db.sh ](https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/install_ts3db.sh) libmariadb.so.2 is not copied from serverfiles/redist/ -> serverfiles/ if the file is not found in serverfiles/, even the libmariadb.so.2 is always included in teamspeak3 server files under redist/.

## To Reproduce

Steps to reproduce the behaviour:
1. preconfigure your mariadb dabatase ( Create user and create database for ts3server ).
2. start installation ( `./ts3server install` )
3. Do you want to use MariaDB/MySQL instead of sqlite? (DB must be pre-configured) [y/N] y
4. Installation will fail because libmariadb.so.2 is not found in serverfiles/
5. `cp serverfiles/redist/libmariadb.so.2 serverfiles/`
6.  start installation ( `./ts3server install` )
7.  Do you want to use MariaDB/MySQL instead of sqlite? (DB must be pre-configured) [y/N] y
8.  Input your database connection information.

```
Configuring TeamSpeak 3 Server for MariaDB/MySQL
=================================
Enter MariaDB hostname: localhost
Enter MariaDB port: 3306
Enter MariaDB username: **********
Enter MariaDB password: **********************************
Enter MariaDB database name: TestDB
=================================
Information! Accepting TeamSpeak license:
 * /home/teamspeak3-server/temp/serverfiles/LICENSE

Getting privilege key
=================================
IMPORANT! Save these details for later.
Starting the TeamSpeak 3 server
TeamSpeak 3 server started, for details please view the log file

------------------------------------------------------------------
                      I M P O R T A N T
------------------------------------------------------------------
               Server Query Admin Account created
         loginname= "serveradmin", password= "**********"
------------------------------------------------------------------


------------------------------------------------------------------
                      I M P O R T A N T
------------------------------------------------------------------
      ServerAdmin privilege key created, please use it to gain
      serveradmin rights for your virtualserver. please
      also check the doc/privilegekey_guide.txt for details.

       token=*******************************************
------------------------------------------------------------------

Stopping the TeamSpeak 3 server.done
    fetching fix.sh...OK

Applying Post-Install Fixes
=================================
Information! No fixes required.
    fetching install_complete.sh...OK
=================================
Install Complete!

To start server type:
./ts3server start

    fetching core_exit.sh...OK

```
9.  ts3db_mariadb.ini will be generated and looks like this ->
```
updating config.
[config]
host='localhost'
port='3306'
username='************************'
password='************************'
database='TestDB'
socket=
```

10. TeamSpeak3 server will be started and connection to the MariaDB fails due incorrect syntax or because socket incorrectly defined, anyways connection fails, and ts3 server fallbacks to the sqlite database and creates one.

11.  Fix the ts3db_mariadb.ini and add your path to the socket.
```
[config]
host='localhost'
port='3306'
username='ts3server'
password='9?3tWSbKkWjt&Y5mX49E%a=5B?e+'
database='teamspeak3'
socket='/var/lib/mysql/mysql.sock'
```

12. start the server once again `./ts3server start` ( Server starts and is now using the MariaDB database correctly. )

## Expected behaviour

User should be able to input the path to the database socket in installation process, so server would work right after installation process with need to find the database connection configuration file and fixing it.

Typo in [install_ts3db.sh](https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/install_ts3db.sh) line - 35 should be fixed so that user does not have to find it and fix it after the installation, and server would function as expected right from the start.

Installation script should try to cp the libmariadb.so.2 file from redist/ and place it in to the correct place if user is trying to configure the ts3 server to use MariaDB while installing.
This can be annoying for the new users, and requires the user to do some googleing to find out what to do.

I have already made required fixes to the [install_ts3db.sh](https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/install_ts3db.sh) and the changes have been pushed to my fork https://github.com/Vis25/LinuxGSM

I will be creating pull request to fix this issue.

Best regards,
visdmin
06.04.2019

### PR DESCRIPTION
**Pull request by Vis25**
# Teamspeak3 server installation with MariaDB fixed.

1. Installation script [ install_ts3db.sh ](https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/install_ts3db.sh) will try to copy the required `libts3db_mariadb.so` from `${serverfiles}/redist/` and place it in `${serverfiles}`, so that user does not have to do that by hand, and redo the installation. 
2. Typo at line 35 removed from - [ install_ts3db.sh ](https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/install_ts3db.sh) `echo "Updating config."` was written in to the database connection configuration file ( ts3db_mariadb.ini ) ( should be outputted to the terminal. ) 
3. Allows user to input database socket path in installation process.
( socket path will be written to the ts3db_mariadb.ini just like all other database connection details. )
( before just empty string was outputted. `echo "socket="` )

Changes have been made to the master branch, sorry about that.
I found out that changes should be done to the develop branch while writing this pull request, so there is issue just comment and let me know, so i will re-do the changes to the develop branch.

Fixes #2260

## Type of change

* [x] Bug fix (change which fixes an issue)
* [ ] New feature (change which adds functionality)
* [ ] New Server (new server added)
* [ ] Refactor (restructures existing code)
* [ ] This change requires a documentation update

## Checklist

* [x] My code follows the style guidelines of this project
* [x] This pull request links to an issue
* [x] I have performed a self-review of my own code
* [x] I have commented my code, particularly in hard to understand areas
* [x] I have made corresponding changes to the documentation if required
* [ ] This pull request uses the `develop` branch as its base 
* [ ] I have squashed commits

### CODE REVIEW

**Comment by Vis25** [comment]
Hey,

I I apologize if i have not followed you ways to commit code to the project, i tried my best to read your documentation, and follow the guide lines, but i have probably made mistakes.

So let me know about the issues so hopefully we can work my idea to the project.

This is first time trying to contribute to GitHub project.

**Comment by dgibbs64** [comment]
IM doing a little refactor while I am reviewing stuff. Very happy with your changes :)

**Comment by dgibbs64** [comment]
Its ready to merge. Just haven't had a chance to sit down with this today. But it will be going in to the develop branch ready for next release. Thanks again for the really detailed issue and pr. Your welcome to contribute any time!

**Comment by Vis25** [comment]
Hi,

I am more than happy to solve problem that effected my on experince with lgsm, and it's always great to make someones else life easyer.

Maybe i will get inspired by lgsm, and start contributing more, there is great chance for that because i love Bash projects 😅

This was also great first time experince with GitHub project, and happy to get involved with great tool that i have used for very long time by my self.

One question regarding the issue that i greated..
Do i close the issue in some point, or do you close the issue, or is the issue automaticaly solved when this pl goes true ? ( Dont want to leave solved issues open )

Best regards,
visdmin

**Comment by dgibbs64** [comment]
I close the issues when I do a release. 👍

**Comment by dgibbs64** [comment]
can you provide your github email. I am working on improved commit messages and need an email to add your info to contributors

https://help.github.com/en/articles/creating-a-commit-with-multiple-authors

**Comment by dgibbs64** [comment]
Changelog ready. @Vis25 please provide github email details then I can merge. 

Co-authored-by: name <name@example.com>

* fix(ts3server): can now add socket info to mariadb.ini
* feat(ts3server): copy libmariadb.so.2 if not found in serverfiles
* feat(install): EULA agreement now handled by install_eula.sh

**Comment by Vis25** [comment]
Hi,

I tried to add my email as public to thw github. Let me know if email is not visible for some reason.

**Comment by dgibbs64** [comment]
Yup I can see it thanks

**Pull request merged**
